<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>2cec6e79-9a9f-4ee6-bdb4-1b93eb9b0f3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#save-selected-pb-step-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='save-selected-pb-step-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9d34fa2c-9e2a-421d-9409-ad4349aba31b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5c9fb395-bb9d-4a90-9e81-bc1132027df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>submitSelectedStep()</value>
      <webElementGuid>f91bd652-96b4-443e-b842-c725ba9d5414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-show</name>
      <type>Main</type>
      <value>(stepSelected.stepType.name !== 'Connectors' &amp;&amp; !stepSelected.stepType.arguments.arguments) || (stepSelected.arguments.connector &amp;&amp; !stepSelected.stepType.arguments.arguments) || (stepSelected.stepType.name !== 'Connectors' &amp;&amp; stepSelected.stepType.arguments.arguments &amp;&amp; stepSelected.stepType.arguments.arguments.connector &amp;&amp; canReadConnectors)</value>
      <webElementGuid>9c9416a2-e565-4e70-86d9-92fc6da4972a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-sm btn btn-primary pull-left margin-right-2</value>
      <webElementGuid>373f8944-75d5-418f-b12c-0bb11a823edf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>save-selected-pb-step-btn</value>
      <webElementGuid>ff48fe29-6c99-4d8f-81f6-fcc91346a828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4b35d85b-2a32-4c9f-a9dd-f9c1eb390436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>78b75cb9-176d-49f6-8915-6dcf102042b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;save-selected-pb-step-btn&quot;)</value>
      <webElementGuid>97bc4ce1-1b4c-498e-b34b-c44fd5d2af4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='save-selected-pb-step-btn']</value>
      <webElementGuid>a494dfb8-982a-46d2-af34-86d85612471a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-form']/div/form/div[2]/button</value>
      <webElementGuid>5d056834-6eab-4ad2-87b8-ade050b3bb75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Message'])[2]/following::button[1]</value>
      <webElementGuid>2c9f6652-3736-4516-b533-8b000177815f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Variables'])[1]/following::button[1]</value>
      <webElementGuid>13c56c5c-086c-4a90-afb6-60e9c1f695e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[18]/preceding::button[1]</value>
      <webElementGuid>2c76daa1-e1ce-4616-8089-bb45267bc9e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dynamic Values'])[1]/preceding::button[2]</value>
      <webElementGuid>f9dd1d62-cc65-4fe7-a1c9-386bb6958f9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>a895965b-8180-425f-aa87-b39e6667ab5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/button</value>
      <webElementGuid>ff4679b0-4721-4b00-a5d3-b1c86159632e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'save-selected-pb-step-btn' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>de775e34-79ca-41e7-9fdd-802e56d8baf1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
