<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Manual</name>
   <tag></tag>
   <elementGuidId>240df871-86d6-484b-b919-cbc978b06104</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.padding-top-bottom-4.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='step-type']/ul/li/a/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bf625a08-99ee-4c57-a25c-06a8fa96b816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-bind</name>
      <type>Main</type>
      <value>stepType.displayName</value>
      <webElementGuid>4cc38450-83f8-403d-b236-ded8cad67a3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>padding-top-bottom-4 ng-binding</value>
      <webElementGuid>081ffd2b-9170-4b26-b4f9-7423631c9b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manual</value>
      <webElementGuid>59e2ca1a-8509-4d60-906d-a0ef012abc18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step-type&quot;)/ul[@class=&quot;stepTypes trigger-step-container ng-scope&quot;]/li[@class=&quot;ng-scope&quot;]/a[@class=&quot;display-flex&quot;]/div[@class=&quot;trigger-step-content&quot;]/div[@class=&quot;padding-top-bottom-4 ng-binding&quot;]</value>
      <webElementGuid>5167ede2-fcac-499a-afed-257eb340f034</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-type']/ul/li/a/div[2]/div</value>
      <webElementGuid>bc95d76a-f750-4db0-9438-4459a6277013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Triggers'])[1]/following::div[3]</value>
      <webElementGuid>9ca0e92f-fd81-44e3-8126-89313d9a907e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CHOOSE A TRIGGER'])[1]/following::div[3]</value>
      <webElementGuid>72a2a1c5-ff00-4fb0-bf82-fa85d3f97a81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='On Create'])[1]/preceding::div[3]</value>
      <webElementGuid>dff0a68b-3475-49f2-976e-a77a09bab70d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Triggered on the creation of records that match the specified criteria.'])[1]/preceding::div[4]</value>
      <webElementGuid>ed23cf88-ac75-4174-bd06-f74cf1e562fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Manual']/parent::*</value>
      <webElementGuid>379e979e-1586-428d-9182-22e206edadbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div[2]/div</value>
      <webElementGuid>e328da2c-592e-4e0e-aaa4-6066b34a1f47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Manual' or . = 'Manual')]</value>
      <webElementGuid>74cb1703-3ade-409a-ac63-6a07d2229f67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
