<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_High</name>
   <tag></tag>
   <elementGuidId>9584b1ee-ccc0-40e6-8ce6-a858cb1d1116</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;severity-option-360&quot;] > div.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Medium'])[1]/following::div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e71226ed-eedc-43f6-b5db-3438ffb0c505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>6a6f4979-985d-4303-914a-8a08d86c95a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> High</value>
      <webElementGuid>7890e56f-4850-4d60-8d19-352d2d6d3bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[@class=&quot;animated fadeIn&quot;]/div[@class=&quot;popover ng-scope ng-isolate-scope bottom lookup fade in&quot;]/div[@class=&quot;popover-inner&quot;]/div[@class=&quot;popover-content&quot;]/ul[@class=&quot;dropdown-menu ng-scope&quot;]/li[@class=&quot;ng-scope&quot;]/a[@class=&quot;option&quot;]/div[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>cdd99759-7460-4c74-ab09-4c72d1e28f85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medium'])[1]/following::div[1]</value>
      <webElementGuid>b99b1fc5-3771-4951-b227-e6a37ac40100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Low'])[2]/following::div[2]</value>
      <webElementGuid>2e46f67c-8be2-4ae5-8901-dc149e889761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Critical'])[1]/preceding::div[1]</value>
      <webElementGuid>735d20e8-ed0c-49ef-98f7-83173fc3d40a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='High']/parent::*</value>
      <webElementGuid>65359dd1-94a6-41dd-9442-eeb2bc2446e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[7]/a/div</value>
      <webElementGuid>4560c8ac-2d20-48d0-9cf2-67e9f4db1c6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' High' or . = ' High')]</value>
      <webElementGuid>4c793c21-0486-4659-95eb-aef3b91e85b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
