<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__stepName</name>
   <tag></tag>
   <elementGuidId>039d4ab0-9804-4ba6-a022-968db0bc0c1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#stepName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='stepName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6698b0df-c439-4c96-ab62-a0b6f64f4324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>stepName</value>
      <webElementGuid>c96b60c9-2d4c-4305-a0f5-1771ea1e0e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e675874b-307c-4443-a0d3-c964d8a92afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-sm form-control ng-pristine ng-empty ng-invalid ng-invalid-required ng-valid-pattern ng-valid-maxlength ng-touched</value>
      <webElementGuid>e05ee777-7056-43eb-977c-42f65f0f52a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>stepName</value>
      <webElementGuid>8f846dce-4e29-452b-88ea-011295a14794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>stepSelected.name</value>
      <webElementGuid>626937e6-4965-404c-9d1c-1581dcfb4ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-required</name>
      <type>Main</type>
      <value>stepSelected</value>
      <webElementGuid>5d9123b4-1e00-447c-a135-1316f5d9b48f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-pattern</name>
      <type>Main</type>
      <value>^[a-zA-Z0-9_ ]*$</value>
      <webElementGuid>a8f11b78-3206-4de9-b8cb-ebfa2d58f4b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-change</name>
      <type>Main</type>
      <value>clearDuplicateValidation(stepForm.stepName.$error.duplicate)</value>
      <webElementGuid>1b0fbf09-66de-411b-a342-47a0c2cdd7cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-maxlength</name>
      <type>Main</type>
      <value>140</value>
      <webElementGuid>6964b42c-9af9-4e31-9da3-3615ac89215f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>8d9985a6-acab-49be-ad87-2ee1fc94dde6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>49dc777a-5172-493b-93b7-bd42ca9e36e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stepName&quot;)</value>
      <webElementGuid>494eb9d0-6d0d-4b3e-abce-885fb28af94c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='stepName']</value>
      <webElementGuid>d21c0874-3218-48eb-adc1-ed7b468a49ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-form']/div/form/fieldset/div[3]/input</value>
      <webElementGuid>59bebd3d-0586-4cf2-ba16-745e65355040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[3]/input</value>
      <webElementGuid>7dc66026-91d1-4fb4-8f45-ea6fd8ea0e57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'stepName' and @type = 'text' and @name = 'stepName']</value>
      <webElementGuid>ed180dd1-370f-4c0c-b3d4-8c5d9d673fb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
