<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__name_1_2_3</name>
   <tag></tag>
   <elementGuidId>57d49d6f-c22a-4011-81ff-33bf74bc952a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#insertDataForm-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='insertDataForm-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>54aa0286-e5e3-4583-8ca4-c0a145c4478b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-hide</name>
      <type>Main</type>
      <value>field.value.includes('resolveVault')</value>
      <webElementGuid>3f78395c-7488-4a8b-9533-af2ceaa61a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-required</name>
      <type>Main</type>
      <value>field.required</value>
      <webElementGuid>d08bd509-9363-45fa-8007-1e6320c6fe2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>insertDataForm-name</value>
      <webElementGuid>5b8a2fe5-33f7-4f16-a1bb-9272a7bbf977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>edb1c8d5-7c6a-4188-a536-42d07701170d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>8cc8f357-4e60-4033-bfc7-c2a03d3f6d45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>$parent.value</value>
      <webElementGuid>f58dc777-486d-4246-ac73-5c795d3d94cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control  ng-isolate-scope jinja-focus ng-not-empty ng-dirty ng-valid ng-valid-required grid-active-filter ng-valid-parse</value>
      <webElementGuid>ce3f22fc-54e6-48be-82d2-31c5bd5aa617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9b64a5a4-fee8-429a-ab07-27892d67500b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-readonly</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>62639534-9146-4d15-ad39-1ed38c3dce99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-change</name>
      <type>Main</type>
      <value>changeMethod(value, field)</value>
      <webElementGuid>6a2dfbba-b191-4c87-b963-befaa2d0bf42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-blur</name>
      <type>Main</type>
      <value>blurMethod(value)</value>
      <webElementGuid>67c3bdd6-d68e-4da6-b7f8-3a0892eb1798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-focus</name>
      <type>Main</type>
      <value>focusMethod($event)</value>
      <webElementGuid>549cfea1-bea5-4d97-a470-ea31393c5548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>::{'input-big': size === 'large', 'input-sm': size === 'small'}</value>
      <webElementGuid>95aa84e9-0f5e-4601-9c3c-4c0cb037bba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enable-jinja</name>
      <type>Main</type>
      <value>enableJinja</value>
      <webElementGuid>7c0dcf84-a0ff-4461-b040-c4ebf81e5b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enable-record-fields</name>
      <type>Main</type>
      <value>enableRecordFields</value>
      <webElementGuid>c38ca5eb-5b16-4902-b6a8-328d48f1cff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ale</value>
      <webElementGuid>d4dbbaeb-715e-4676-996c-4951f83fe704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-controller</name>
      <type>Main</type>
      <value>JinjaFocusCtrl</value>
      <webElementGuid>8ef081d8-5338-4c8c-855a-53cfe961dbba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>onClick($event)</value>
      <webElementGuid>33942851-1272-4dec-b499-f7aa4cdd9ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-mousedown</name>
      <type>Main</type>
      <value>onMouseDown($event)</value>
      <webElementGuid>f8917880-48c3-48be-898e-a41f4f4663ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8d47b2be-3c5d-49c0-9838-b2811d1c7d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>26f463ff-599b-4970-949f-b874dd3baf70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1d840340-53e4-4e5d-9541-3b8a11ce2b6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;insertDataForm-name&quot;)</value>
      <webElementGuid>ed78c7fa-7372-4c4d-9205-f5ba5fabba05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='insertDataForm-name']</value>
      <webElementGuid>bd2e646e-0fda-4e15-a0a6-79b51d963ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-form']/div/form/fieldset/div[5]/div/div[2]/div[3]/div/div/div/div/div[2]/div/div[3]/div/input</value>
      <webElementGuid>0e039225-546b-4fb3-8390-97ab89dd27b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>61584101-d67b-473a-aee8-81ae930f8319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'insertDataForm-name' and @type = 'text' and @name = 'name' and @title = 'Ale']</value>
      <webElementGuid>d9480c1e-b657-4b9e-83b8-85c4e3ee3768</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
