<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select an OptionAlertsAnnouncementsA_588099</name>
   <tag></tag>
   <elementGuidId>4b350a78-79e2-4b19-b823-799dc382c314</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#stepModel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='stepModel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2adb0cac-46b7-4bbb-8e9a-d54eb6ad255f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>stepModel</value>
      <webElementGuid>6cedc4f0-819d-4805-b2ce-5328ac87f1b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required</value>
      <webElementGuid>48fd6d86-637d-4739-9cd4-d983316a51b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>stepModel</value>
      <webElementGuid>470c0f9e-82ee-42ab-b5d2-807143a677af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-options</name>
      <type>Main</type>
      <value>module.typeIri as module.name for module in modules | playbookModules</value>
      <webElementGuid>e39ffc30-ed24-4627-ab63-51b05a60748a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-change</name>
      <type>Main</type>
      <value>selectModule()</value>
      <webElementGuid>40f4a68a-d45d-49eb-87eb-40be8e12a654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>$parent.selectedModule</value>
      <webElementGuid>d5cb4e92-628a-43e3-a90a-e3b9a1444755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>090964c1-81b9-4283-9407-0b7b1e5e2f05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select an OptionAlertsAnnouncementsAssetsAttachmentsCampaignsCommentCommunicationsCompaniesCredit CardsData ArchivalEmail TemplatesEventsFilesHuntsIncidentsIndicatorsQueuesRoutersShiftsSLA TemplatesSolution PacksTasksTenantsWar Rooms</value>
      <webElementGuid>9a5ef98e-b591-498d-a3de-6b9a50eedecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stepModel&quot;)</value>
      <webElementGuid>a5f97ed8-9701-4f8c-86ff-d56ea6e27144</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='stepModel']</value>
      <webElementGuid>13ee4aca-d0d0-4289-a220-968532378fc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-form']/div/form/fieldset/div[5]/div/div/select</value>
      <webElementGuid>307db93a-9918-4358-8746-b3ce901c9c93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::select[1]</value>
      <webElementGuid>09fc4e73-3b0a-4ab1-a485-8a006ad677f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field is required.'])[2]/preceding::select[1]</value>
      <webElementGuid>d562b4c3-e8b5-4be8-92cf-6d31f1a70e67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fields'])[1]/preceding::select[1]</value>
      <webElementGuid>252a5563-7bcf-4cba-81e1-8b839a95cf09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>6b3009ee-172b-4a0f-a204-3c54af5e4f41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'stepModel' and @name = 'stepModel' and (text() = 'Select an OptionAlertsAnnouncementsAssetsAttachmentsCampaignsCommentCommunicationsCompaniesCredit CardsData ArchivalEmail TemplatesEventsFilesHuntsIncidentsIndicatorsQueuesRoutersShiftsSLA TemplatesSolution PacksTasksTenantsWar Rooms' or . = 'Select an OptionAlertsAnnouncementsAssetsAttachmentsCampaignsCommentCommunicationsCompaniesCredit CardsData ArchivalEmail TemplatesEventsFilesHuntsIncidentsIndicatorsQueuesRoutersShiftsSLA TemplatesSolution PacksTasksTenantsWar Rooms')]</value>
      <webElementGuid>105566da-53ca-4213-89a2-94ae1925a4c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
