<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Alerts</name>
   <tag></tag>
   <elementGuidId>d0cc14c3-d516-4d86-8197-37bdec4142a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.new-truncate-ellipsis.ng-scope > a.ng-binding.ng-scope</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>adeeea0b-dc03-4436-8e08-e69b93a15ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-if</name>
      <type>Main</type>
      <value>!item.openInNewTab</value>
      <webElementGuid>f907c2eb-6b3d-4999-91c3-80055eb66a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui-sref</name>
      <type>Main</type>
      <value>main.modules.list({&quot;module&quot;:&quot;alerts&quot;})</value>
      <webElementGuid>c34d840c-3f51-4d13-b3f0-0ed19dc4107d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ui-sref-opts</name>
      <type>Main</type>
      <value>{inherit: false}</value>
      <webElementGuid>18adab6e-b93e-4a4b-aa75-68bb45c9b457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Alerts</value>
      <webElementGuid>8ca55d7d-e00b-4d35-a7d8-521563a49fff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding ng-scope</value>
      <webElementGuid>aef973cb-c544-4753-ac97-3d600d6435b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/modules/alerts</value>
      <webElementGuid>8db997c9-6ccc-4c04-a91a-5ee8a5600485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alerts</value>
      <webElementGuid>0b4e1fc1-e01e-4cba-9419-7b012f0b3c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navigation-wrapper&quot;)/div[@class=&quot;nav-top-bar navigationHeight nav-full-width&quot;]/div[@class=&quot;slim-scroll-wrapper&quot;]/nav[@class=&quot;mini-nav ng-scope&quot;]/ul[@class=&quot;navigation&quot;]/li[@class=&quot;animate-show-hide ng-scope&quot;]/ul[@class=&quot;animate-show-hide ng-scope ng-hide&quot;]/li[@class=&quot;new-truncate-ellipsis ng-scope&quot;]/a[@class=&quot;ng-binding ng-scope&quot;]</value>
      <webElementGuid>754a6071-18d0-4a6e-b07a-93161c22663a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navigation-wrapper']/div[2]/div/nav/ul/li[3]/ul/li[2]/a</value>
      <webElementGuid>3ac9b460-b0cb-4bc3-b6ca-50538e03eef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Alerts')]</value>
      <webElementGuid>d5391f0f-7745-483c-bd07-a7b5eceb2a12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incident Response'])[1]/following::a[1]</value>
      <webElementGuid>0cdac616-cd06-4722-819d-4d67569da831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Queue &amp; Shift Management'])[1]/following::a[3]</value>
      <webElementGuid>b984148e-698e-47d5-9f2f-36e306400977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incidents'])[1]/preceding::a[1]</value>
      <webElementGuid>35c362a8-0a57-4b09-a624-284704c24b1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tasks'])[1]/preceding::a[2]</value>
      <webElementGuid>04bf3e23-bad0-48b5-b3c3-d4d2d5f97d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Alerts']/parent::*</value>
      <webElementGuid>7b31385b-4a8a-4adc-baf8-411de117a265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/modules/alerts')]</value>
      <webElementGuid>efef5e1e-5206-4c07-bbcd-471e4ea1c7f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li[2]/a</value>
      <webElementGuid>2a411a15-dab1-4892-86a8-891708eeec87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Alerts' and @href = '/modules/alerts' and (text() = 'Alerts' or . = 'Alerts')]</value>
      <webElementGuid>aa1ff29d-98db-46aa-b7ff-dbbbd087603d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
