<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel_1_2</name>
   <tag></tag>
   <elementGuidId>bde97685-0fdf-47aa-88d2-89c22475bdec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cancel-debug-playbook-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='cancel-debug-playbook-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f08413df-9f04-4b86-8e0b-0ab3ceb6b458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5924b1cf-b4da-4bd0-8958-b2eeb8d0cc02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default margin-left-sm btn-sm</value>
      <webElementGuid>20ebbdd4-5e17-4708-9222-e17497499b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>clearSelectedStep(); clearPreviousSelection()</value>
      <webElementGuid>28387b28-7136-4c8e-8097-f0c8878c12c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cancel-debug-playbook-btn</value>
      <webElementGuid>74b8f485-a575-41e1-ad38-9f7a796cc4fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>90210f17-6176-473c-aaf1-e8e37653de3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cancel-debug-playbook-btn&quot;)</value>
      <webElementGuid>cda3c6e7-c0d6-4b38-9f74-0b75ce946898</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='cancel-debug-playbook-btn']</value>
      <webElementGuid>7e137cb9-b481-4ec3-87d4-a7a6a4e034d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-form']/div/div/div/form/div[3]/div[2]/button[2]</value>
      <webElementGuid>199d8cd1-7562-438b-9d4a-532855d6a285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trigger Playbook'])[1]/following::button[1]</value>
      <webElementGuid>a42e036d-8afb-4471-829e-2f8086a42be0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='characters selected'])[1]/following::button[2]</value>
      <webElementGuid>1b72f75e-e1d9-44bb-96ee-7558a88fe070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ Add Step Description'])[1]/preceding::button[2]</value>
      <webElementGuid>0c050865-4dd4-4f63-b528-83e97cff6da7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/button[2]</value>
      <webElementGuid>e56956f9-750a-4c00-b484-8040e5fd44c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'cancel-debug-playbook-btn' and (text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>75a547ca-8342-4402-b9b5-7e4b0859ab93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
