<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Mode_trigger-playbook-button</name>
   <tag></tag>
   <elementGuidId>50fd30d0-a01f-4921-94f4-df739f9489b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#trigger-playbook-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='trigger-playbook-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b7c9d9c1-52ce-4187-a2f7-278e16c639d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>trigger-playbook-button</value>
      <webElementGuid>04364b60-dc6c-4381-b1ed-6a4fa8f315c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>openDebugPlaybook()</value>
      <webElementGuid>38e69a53-cf8d-451e-81cf-4424c80418e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4ab9cf99-e87b-4ac3-8629-e7baf4ff7346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-sm</value>
      <webElementGuid>11d872e9-70df-47c1-8093-61042704858f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Trigger Playbook With Sample Data</value>
      <webElementGuid>273f15c6-ab6a-494e-918a-7d70271df227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{'padding-tb-4': $parent.showPBVersionText}</value>
      <webElementGuid>3a2b90f0-7ede-4a92-8d6b-c89a9996204f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-disabled</name>
      <type>Main</type>
      <value>$parent.loading</value>
      <webElementGuid>496306c5-ef0b-40a3-93a0-4ebbf46ce672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trigger-playbook-button&quot;)</value>
      <webElementGuid>911da262-45a8-4c83-a157-ea943056c3cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='trigger-playbook-button']</value>
      <webElementGuid>022dfd30-5525-4ac7-8c0b-b0da6f46edd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='debug']/button</value>
      <webElementGuid>e01dff15-3007-4eee-a917-6dd811533ced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mode'])[1]/following::button[7]</value>
      <webElementGuid>e301c51a-7163-4663-b524-1043d1023554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INFO'])[1]/following::button[7]</value>
      <webElementGuid>ce44ecf8-a8b5-465b-a62d-6d491c98872f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tools'])[1]/preceding::button[1]</value>
      <webElementGuid>3cea4b72-3be7-4ba9-8e52-25356b13dd90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/button</value>
      <webElementGuid>2a77fbd4-0c8c-4b57-94e9-6d3b227a3f32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'trigger-playbook-button' and @type = 'button' and @title = 'Trigger Playbook With Sample Data']</value>
      <webElementGuid>06192a9b-ac5b-4446-842f-ce4b60dd7609</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
