<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_High</name>
   <tag></tag>
   <elementGuidId>b211788a-2421-49ae-94fa-b8fc57d6a627</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#insertDataForm-severity-lookup-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='insertDataForm-severity-lookup-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ea847213-3953-4272-a135-0cc5e0a902fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lookup-btn ng-pristine ng-valid ng-not-empty ng-valid-required btn btn-link ng-touched</value>
      <webElementGuid>1d5cbff4-9770-4cf2-b0bf-4160d137fbd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>insertDataForm-severity-lookup-btn</value>
      <webElementGuid>4a611a18-da86-4adb-a783-eb56e46534ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-popover-class</name>
      <type>Main</type>
      <value>lookup</value>
      <webElementGuid>8c824dba-92ee-4c8a-a08c-fa7a88c34373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-disabled</name>
      <type>Main</type>
      <value>isDisabled</value>
      <webElementGuid>70e8f160-d315-4586-906a-7b4b3d3b61fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>bbdeca8b-18ff-4bad-9405-e1f2fda3c4c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>severity</value>
      <webElementGuid>835690c1-12eb-45de-be70-5e3959d823d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-required</name>
      <type>Main</type>
      <value>field.required</value>
      <webElementGuid>7e7c2c05-7102-48d7-8b8d-516fa2aa0eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-popover-append-to-body</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e62942b3-477c-4cdf-8efd-f60fcbdd7d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uib-popover-template</name>
      <type>Main</type>
      <value>dynamicPopover.templateUrl</value>
      <webElementGuid>6f26a713-5516-4408-bdd1-3605cdee30ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-popover-trigger</name>
      <type>Main</type>
      <value>'outsideClick'</value>
      <webElementGuid>c4624d2b-037f-403f-a777-c8ec72e11de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-popover-is-open</name>
      <type>Main</type>
      <value>opened</value>
      <webElementGuid>d2dde9d6-7c37-41ec-a85d-8627905c6933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-popover-title</name>
      <type>Main</type>
      <value>Severity</value>
      <webElementGuid>f2960017-d73f-441a-856e-a8440133dbcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-popover-placement</name>
      <type>Main</type>
      <value>auto bottom</value>
      <webElementGuid>3e1c501f-afc1-458a-b2b6-f9819f2b2da6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b88c1f66-84d9-4c11-885b-87d7a50be7e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>buttonClasses</value>
      <webElementGuid>e94bb26a-ed3a-4d5d-af96-a63f03b586d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>onOpen($event)</value>
      <webElementGuid>8ef5bfb2-4a95-44a5-8124-e9175b3e7f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9ec4185f-6d19-4a17-a11c-30cf6385aea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  High </value>
      <webElementGuid>aa7ee760-63e6-404d-920a-0100f5c7b4d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;insertDataForm-severity-lookup-btn&quot;)</value>
      <webElementGuid>4847c6bd-f7e8-4f82-9e72-81f39bd51571</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='insertDataForm-severity-lookup-btn']</value>
      <webElementGuid>bd97af59-c671-4291-931b-e39b1cf7bf05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-form']/div/form/fieldset/div[5]/div/div[2]/div[3]/div/div/div/div/div[8]/div/div[3]/div/div/div/button</value>
      <webElementGuid>15ebd7b0-0a1f-4130-aba1-a1616b317219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='{}'])[8]/following::button[1]</value>
      <webElementGuid>13395974-ecc2-4e38-851f-7439fa9044cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='{}'])[9]/preceding::button[1]</value>
      <webElementGuid>b13a51f2-fe93-4871-82dd-e7252e7dab60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[3]/div/div/div/button</value>
      <webElementGuid>11f2a7b5-8743-465b-addf-f0befdae7489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'insertDataForm-severity-lookup-btn' and @name = 'severity' and @type = 'button' and (text() = '  High ' or . = '  High ')]</value>
      <webElementGuid>6b5bc543-aaa3-4a48-976b-6ecdebffe973</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
