<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>19c2d538-418a-46a0-b808-889fe34dbd0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#save-selected-pb-step-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='save-selected-pb-step-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d57d1fe0-62aa-411d-9f89-2242e7ae45b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4719e27a-b323-4d03-8f4e-a5b91a0dcb8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>submitSelectedStep()</value>
      <webElementGuid>dbe77b5a-2e2d-42dd-8db2-3588a3216a57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-show</name>
      <type>Main</type>
      <value>(stepSelected.stepType.name !== 'Connectors' &amp;&amp; !stepSelected.stepType.arguments.arguments) || (stepSelected.arguments.connector &amp;&amp; !stepSelected.stepType.arguments.arguments) || (stepSelected.stepType.name !== 'Connectors' &amp;&amp; stepSelected.stepType.arguments.arguments &amp;&amp; stepSelected.stepType.arguments.arguments.connector &amp;&amp; canReadConnectors)</value>
      <webElementGuid>a11ffd10-6ce9-45fa-b3b8-e134eea2a184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-sm btn btn-primary pull-left margin-right-2</value>
      <webElementGuid>c6524a28-fc71-426c-a3e2-01566f1ceb03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>save-selected-pb-step-btn</value>
      <webElementGuid>8259b733-4304-448a-aadd-9d64afb7dfa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>39825abd-cc48-426d-b730-5c37dcb29065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>c31d7db0-4fba-44f8-b436-60afb2d0f280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;save-selected-pb-step-btn&quot;)</value>
      <webElementGuid>fd361179-21fa-4d9d-b141-763fe65e0ee1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='save-selected-pb-step-btn']</value>
      <webElementGuid>d6ece012-cd43-4659-ac24-1649934a8062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-form']/div/form/div[2]/button</value>
      <webElementGuid>1895ecdc-f05f-4dcc-911f-4d0717954fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Message'])[2]/following::button[1]</value>
      <webElementGuid>96ca62ae-3c5f-47ab-a56d-e305b6948559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Variables'])[1]/following::button[1]</value>
      <webElementGuid>71f38e24-6a64-4f89-b48b-ea9d2b21495a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[18]/preceding::button[1]</value>
      <webElementGuid>e089d77c-c2c0-4051-8411-6a12affe2bbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dynamic Values'])[1]/preceding::button[2]</value>
      <webElementGuid>709938fd-07de-4e7c-94f3-a35c2d04700d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>3eabd628-420b-4b92-a945-2388cbd4b747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/button</value>
      <webElementGuid>182278e0-cb30-4cbe-adb1-48df4a593ee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'save-selected-pb-step-btn' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>c4012133-4b10-48bd-afcc-e0822c1e3b7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
