<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Low</name>
   <tag></tag>
   <elementGuidId>8bdd1a22-f98f-4393-ac81-563f58fe8d91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#insertDataForm-severity-lookup-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='insertDataForm-severity-lookup-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ee49f2da-631d-475d-9f34-9332f29a42be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lookup-btn ng-pristine ng-valid ng-not-empty ng-valid-required btn btn-link ng-touched</value>
      <webElementGuid>56a5148f-196b-4fae-90ad-b4679f5ab65a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>insertDataForm-severity-lookup-btn</value>
      <webElementGuid>04e3c7cd-8fdc-45d8-bca3-a8bff0511798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-popover-class</name>
      <type>Main</type>
      <value>lookup</value>
      <webElementGuid>29f6f4b8-9fbe-4f5e-a1f7-4efe7c89fe1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-disabled</name>
      <type>Main</type>
      <value>isDisabled</value>
      <webElementGuid>ee83a1ef-4b70-4790-a5d2-c3369956f02b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>5220f6e0-f473-4c31-af68-e2a54bba304c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>severity</value>
      <webElementGuid>c9255947-a978-4743-97b8-41f431ef6a15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-required</name>
      <type>Main</type>
      <value>field.required</value>
      <webElementGuid>cf3dc109-68d4-4d7f-b552-a1f7cf892c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-popover-append-to-body</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1ecbc462-0097-4e37-8b77-fa2d7ac401f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uib-popover-template</name>
      <type>Main</type>
      <value>dynamicPopover.templateUrl</value>
      <webElementGuid>2bb2b59d-f264-4cd8-9fc2-8ce04108c80a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-popover-trigger</name>
      <type>Main</type>
      <value>'outsideClick'</value>
      <webElementGuid>51fb90c0-99ac-428f-8449-dbd8c9a7d36d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-popover-is-open</name>
      <type>Main</type>
      <value>opened</value>
      <webElementGuid>af1d33b4-06ae-4090-ac2e-451f7884313b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-popover-title</name>
      <type>Main</type>
      <value>Severity</value>
      <webElementGuid>6e1834c6-812e-40d0-9fe0-f5a0199402f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-popover-placement</name>
      <type>Main</type>
      <value>auto bottom</value>
      <webElementGuid>ebca9192-cd51-4e76-b4d9-aced8ba09c51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b153883e-ccbe-4dff-907d-2192f39dddc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>buttonClasses</value>
      <webElementGuid>98104505-cc0c-4c30-b705-e7563574604c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>onOpen($event)</value>
      <webElementGuid>2d86a108-498a-4250-a66f-64c51cc3c469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a9a80afb-ad8d-4298-bcd5-b129c994f488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Low </value>
      <webElementGuid>f133e1a8-a1f8-4da2-862c-7844fb04bcba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;insertDataForm-severity-lookup-btn&quot;)</value>
      <webElementGuid>bf269fb1-3a6b-41c0-8a90-928284384cd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='insertDataForm-severity-lookup-btn']</value>
      <webElementGuid>b225f679-aa23-45a5-ab36-d2ba5c4e766f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-form']/div/form/fieldset/div[5]/div/div[2]/div[3]/div/div/div/div/div[8]/div/div[3]/div/div/div/button</value>
      <webElementGuid>7741e71d-960e-46b1-81dc-aefe93ba33cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='{}'])[8]/following::button[1]</value>
      <webElementGuid>98771ec9-ce10-4913-90fe-41b8d7429e4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='{}'])[9]/preceding::button[1]</value>
      <webElementGuid>b88f13e0-3bd5-4b9a-a376-0f91c69d7330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[3]/div/div/div/button</value>
      <webElementGuid>ee2e12bb-b0dd-40ac-983a-957bb7a9809a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'insertDataForm-severity-lookup-btn' and @name = 'severity' and @type = 'button' and (text() = '  Low ' or . = '  Low ')]</value>
      <webElementGuid>ee62dcec-5632-4c07-9579-2dd2ed4b6ac3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
