<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel</name>
   <tag></tag>
   <elementGuidId>19ccbc19-9245-4509-b040-0651e6023e61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cancel-selected-pb-step-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='cancel-selected-pb-step-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>80bd683c-c9c6-49c3-bb02-12315686eb5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9e7799c4-4f5c-4e1f-8293-6968cebb09c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default pull-left btn-sm</value>
      <webElementGuid>27c29e94-a065-4b40-a60b-b040622922c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>clearSelectedStep()</value>
      <webElementGuid>5d184e54-b261-4bec-9424-512caed5b58a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cancel-selected-pb-step-btn</value>
      <webElementGuid>6a98e8bd-ce3a-4d50-8fa2-f6c0de4c9e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>49350cee-c97e-4967-bbd9-e1ba28b66963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cancel-selected-pb-step-btn&quot;)</value>
      <webElementGuid>787332cd-d5f2-473b-895a-28bf66471942</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='cancel-selected-pb-step-btn']</value>
      <webElementGuid>0e73913d-ef7d-4e95-ade2-6160e345e9a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-form']/div/form/div[2]/button[2]</value>
      <webElementGuid>a1c7b49d-d39e-4c82-ba97-bcc1c7bf9591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::button[1]</value>
      <webElementGuid>14a5b360-d6c9-4ed0-889e-12bda99cd37b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/following::button[2]</value>
      <webElementGuid>0e08e89c-0bb7-4f45-a0df-d2d8e5634f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dynamic Values'])[1]/preceding::button[1]</value>
      <webElementGuid>a947c3fb-771d-4556-bbb8-01c69adfa06c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expressions'])[1]/preceding::button[1]</value>
      <webElementGuid>84a6b9fa-88de-40d8-aea8-9e376323eea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/button[2]</value>
      <webElementGuid>3fbb9e74-7754-4557-86c3-17a56118d5bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'cancel-selected-pb-step-btn' and (text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>c58a885e-e37f-467e-98a2-e4dd87d822f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
