<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel_1</name>
   <tag></tag>
   <elementGuidId>d2c21738-8cf6-47a4-9e5f-125857b7ad3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#close-selected-pb-step-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='close-selected-pb-step-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>62373b41-e576-4ffa-a6da-925845928e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>93ca154f-8ccc-4e6a-a2f6-a19983598dc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-sm btn btn-default pull-right</value>
      <webElementGuid>e49d2f98-8eb7-4550-93b0-01c13b880d72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>clearPlaceholderStep()</value>
      <webElementGuid>c1eaf247-7764-4efc-a487-7721766da3cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-show</name>
      <type>Main</type>
      <value>playbook.triggerStep</value>
      <webElementGuid>d2276d1b-c82b-40d7-b716-273179839aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>close-selected-pb-step-btn</value>
      <webElementGuid>355d1824-5dc9-4116-b06d-184bcce846d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e26d6491-9f4b-42dd-9763-66abcd30815c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>e943c924-9bfa-4daa-b4db-ac4df7fdb83c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;close-selected-pb-step-btn&quot;)</value>
      <webElementGuid>74d6b538-7c21-46d1-8773-982b080b543c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='close-selected-pb-step-btn']</value>
      <webElementGuid>1011e772-0837-4671-bae9-d74521c0b308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-type']/button</value>
      <webElementGuid>b08e1f8e-8f9e-46fb-9e01-888159f25dbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Steps'])[1]/following::button[1]</value>
      <webElementGuid>23dfa996-b5d3-47ad-b5a6-0052af563753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Create Alert Record Playbook'])[2]/following::button[2]</value>
      <webElementGuid>b106933e-60a3-4aee-883e-23251a7618d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Triggers'])[1]/preceding::button[1]</value>
      <webElementGuid>1524180c-1986-4e88-be5a-0e85f78ce556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manual'])[1]/preceding::button[1]</value>
      <webElementGuid>dc726e88-9928-43ee-adb4-fba98437701c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/button</value>
      <webElementGuid>a00bb903-0548-4dd6-a22d-3bf27388da8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'close-selected-pb-step-btn' and (text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>11425d08-c491-4bc6-acfd-34e8c3ac39a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
