<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Manual</name>
   <tag></tag>
   <elementGuidId>cb15d0ac-0699-47c7-bf6f-3e56c28f842b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.padding-top-bottom-4.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='step-type']/ul/li/a/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>be71545d-6362-42d1-8ff2-e72ae8969f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-bind</name>
      <type>Main</type>
      <value>stepType.displayName</value>
      <webElementGuid>2f12d2d6-4751-492e-b6b3-f935569404fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>padding-top-bottom-4 ng-binding</value>
      <webElementGuid>c233f497-46f1-4cc4-8e24-eb13080da264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manual</value>
      <webElementGuid>a9486cf3-7d47-4236-a0d4-1ecd2559844f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step-type&quot;)/ul[@class=&quot;stepTypes trigger-step-container ng-scope&quot;]/li[@class=&quot;ng-scope&quot;]/a[@class=&quot;display-flex&quot;]/div[@class=&quot;trigger-step-content&quot;]/div[@class=&quot;padding-top-bottom-4 ng-binding&quot;]</value>
      <webElementGuid>900ea060-0289-4b7d-88a0-542dd1e36770</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-type']/ul/li/a/div[2]/div</value>
      <webElementGuid>0fd43164-bf06-4844-9325-64e06d5eeef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Triggers'])[1]/following::div[3]</value>
      <webElementGuid>2c699fb4-1beb-442f-9b7c-e3c53e25fc38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CHOOSE A TRIGGER'])[1]/following::div[3]</value>
      <webElementGuid>d515d0af-30ae-4378-93c4-4a56aa630668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='On Create'])[1]/preceding::div[3]</value>
      <webElementGuid>73653945-2169-4506-a5ee-017da4e456e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Triggered on the creation of records that match the specified criteria.'])[1]/preceding::div[4]</value>
      <webElementGuid>b04faaf8-fc32-43f3-ab3e-abf4aef50bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Manual']/parent::*</value>
      <webElementGuid>40bad8f8-c7a2-437f-a4b4-f4460f5e7976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div[2]/div</value>
      <webElementGuid>199c4690-6a89-4509-9c95-35a8e17ba496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Manual' or . = 'Manual')]</value>
      <webElementGuid>fcd52916-829e-44b1-9536-9942f608ad9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
