<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_StepsCancelThe Trigger step decides how_4b174d</name>
   <tag></tag>
   <elementGuidId>c0870987-0052-40c0-92ff-87b0412eafee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dynamic-step-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dynamic-step-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>593a9f3e-eeae-4c7b-b24e-bc892686cc7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>transcludeClass</value>
      <webElementGuid>958b9fab-9ac5-48ee-858b-3a2b0ae649a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>transclude-container step-input-container</value>
      <webElementGuid>cba2f1a2-e2bd-4804-9c59-3dc05be7a053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dynamic-step-container</value>
      <webElementGuid>6c2870ee-3bbd-443f-8e18-fecffba3d555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>StepsCancelThe Trigger step decides how a playbook starts in FortiSOAR™. Multiple ways of triggering a playbook are available from which users can choose the most suitable method.CHOOSE A TRIGGERTriggersManualTriggered when the user selects record(s) and then selects the playbook from the &quot;Execute&quot; list.On CreateTriggered on the creation of records that match the specified criteria.On UpdateTriggered on the updation of records that match the specified criteria.ReferencedTriggered from another playbook using a &quot;Reference Playbook&quot; step or from a schedule.Custom API EndpointTriggered from an API request to a custom endpoint.On DeleteTriggered on the deletion of records that match the specified criteria.Pre-Create TriggerPre-Update TriggerPre-Delete TriggerCoreCreate RecordUpdate RecordFind RecordsIngest Bulk FeedSet VariableSet Playbook ResultEvaluateDecisionWaitApprovalManual TaskManual DecisionManual InputExecuteConnectorUtilitiesCode SnippetDatabase ConnectorRun Utility FunctionsReferencesDatabase QueryRemote CommandReference a PlaybookReference Remote PlaybookMap PlaybookMake API CallEmailSend EmailSend EmailFetch EmailAuthenticationSet API KeysFilesSFTPCreate File From StringDownload File from URLCreate Attachment From FileTrigger Playbook With Sample DataChoose a way to provide sample input data to trigger playbook with Last Run DataNot Available Record Input/CustomTrigger Step -  Mock OutputDisabledTrigger Playbook CancelManual  This step is unavailable to use in your environment. BackStep Name*                           Cannot be more than 140 characters.Only alphanumeric character, space and _ is allowed. &quot;Start&quot; step name already exists.+ Add Step DescriptionStep DescriptionMax 1024 character allowed.Trigger Button Label Execution Behaviour Requires record input to runRun Mode Run once for all selected records Run separately for each selected recordsChoose record modules on which the playbook would be available on × AlertsAnnouncementsAssetsAttachmentsCampaignsCommentCommunicationsCompaniesContent HubCredit CardsData ArchivalEmail TemplatesEventsFilesHuntsIncidentsIndicatorsQueuesRoutersShiftsSLA TemplatesSolution PacksTasksTenantsWar Rooms+ Configure Visibility ConditionsDisplay ConditionsDisplay the manual trigger only when the specified conditions are met.AlertsTrigger Condition:Select Logical OperatorALL OF THE BELOW ARE TRUE (AND)ANY OF THE BELOW IS TRUE (OR) ADD CONDITION  ADD CONDITIONS GROUPResulting Value:Select a valueTrueFalse                            Does not require a record input to runUser PromptInput PromptOpens a custom form on the playbook trigger to accept user input. Add FieldStep Utilities None addedLoop When Message Mock Output Variables   Message Save Cancel </value>
      <webElementGuid>f90b78e7-1720-4536-8834-baedbe90eca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dynamic-step-container&quot;)</value>
      <webElementGuid>5a3b7c18-f846-430b-b3ad-b5372e48dacd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dynamic-step-container']</value>
      <webElementGuid>4fde5030-dcb2-4f51-b0d5-081306671509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-collections']/div</value>
      <webElementGuid>35aaa59b-8372-4db2-b5b8-012556b4cac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Create Alert Record Playbook'])[2]/following::div[9]</value>
      <webElementGuid>1cfd0e30-c6c4-48c5-86d2-61b011c6e03e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collections'])[2]/following::div[11]</value>
      <webElementGuid>337bd625-858a-40b0-be8d-6f0bcf914405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div</value>
      <webElementGuid>3986465e-ff31-4349-85d7-1e80f9a68f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dynamic-step-container' and (text() = 'StepsCancelThe Trigger step decides how a playbook starts in FortiSOAR™. Multiple ways of triggering a playbook are available from which users can choose the most suitable method.CHOOSE A TRIGGERTriggersManualTriggered when the user selects record(s) and then selects the playbook from the &quot;Execute&quot; list.On CreateTriggered on the creation of records that match the specified criteria.On UpdateTriggered on the updation of records that match the specified criteria.ReferencedTriggered from another playbook using a &quot;Reference Playbook&quot; step or from a schedule.Custom API EndpointTriggered from an API request to a custom endpoint.On DeleteTriggered on the deletion of records that match the specified criteria.Pre-Create TriggerPre-Update TriggerPre-Delete TriggerCoreCreate RecordUpdate RecordFind RecordsIngest Bulk FeedSet VariableSet Playbook ResultEvaluateDecisionWaitApprovalManual TaskManual DecisionManual InputExecuteConnectorUtilitiesCode SnippetDatabase ConnectorRun Utility FunctionsReferencesDatabase QueryRemote CommandReference a PlaybookReference Remote PlaybookMap PlaybookMake API CallEmailSend EmailSend EmailFetch EmailAuthenticationSet API KeysFilesSFTPCreate File From StringDownload File from URLCreate Attachment From FileTrigger Playbook With Sample DataChoose a way to provide sample input data to trigger playbook with Last Run DataNot Available Record Input/CustomTrigger Step -  Mock OutputDisabledTrigger Playbook CancelManual  This step is unavailable to use in your environment. BackStep Name*                           Cannot be more than 140 characters.Only alphanumeric character, space and _ is allowed. &quot;Start&quot; step name already exists.+ Add Step DescriptionStep DescriptionMax 1024 character allowed.Trigger Button Label Execution Behaviour Requires record input to runRun Mode Run once for all selected records Run separately for each selected recordsChoose record modules on which the playbook would be available on × AlertsAnnouncementsAssetsAttachmentsCampaignsCommentCommunicationsCompaniesContent HubCredit CardsData ArchivalEmail TemplatesEventsFilesHuntsIncidentsIndicatorsQueuesRoutersShiftsSLA TemplatesSolution PacksTasksTenantsWar Rooms+ Configure Visibility ConditionsDisplay ConditionsDisplay the manual trigger only when the specified conditions are met.AlertsTrigger Condition:Select Logical OperatorALL OF THE BELOW ARE TRUE (AND)ANY OF THE BELOW IS TRUE (OR) ADD CONDITION  ADD CONDITIONS GROUPResulting Value:Select a valueTrueFalse                            Does not require a record input to runUser PromptInput PromptOpens a custom form on the playbook trigger to accept user input. Add FieldStep Utilities None addedLoop When Message Mock Output Variables   Message Save Cancel ' or . = 'StepsCancelThe Trigger step decides how a playbook starts in FortiSOAR™. Multiple ways of triggering a playbook are available from which users can choose the most suitable method.CHOOSE A TRIGGERTriggersManualTriggered when the user selects record(s) and then selects the playbook from the &quot;Execute&quot; list.On CreateTriggered on the creation of records that match the specified criteria.On UpdateTriggered on the updation of records that match the specified criteria.ReferencedTriggered from another playbook using a &quot;Reference Playbook&quot; step or from a schedule.Custom API EndpointTriggered from an API request to a custom endpoint.On DeleteTriggered on the deletion of records that match the specified criteria.Pre-Create TriggerPre-Update TriggerPre-Delete TriggerCoreCreate RecordUpdate RecordFind RecordsIngest Bulk FeedSet VariableSet Playbook ResultEvaluateDecisionWaitApprovalManual TaskManual DecisionManual InputExecuteConnectorUtilitiesCode SnippetDatabase ConnectorRun Utility FunctionsReferencesDatabase QueryRemote CommandReference a PlaybookReference Remote PlaybookMap PlaybookMake API CallEmailSend EmailSend EmailFetch EmailAuthenticationSet API KeysFilesSFTPCreate File From StringDownload File from URLCreate Attachment From FileTrigger Playbook With Sample DataChoose a way to provide sample input data to trigger playbook with Last Run DataNot Available Record Input/CustomTrigger Step -  Mock OutputDisabledTrigger Playbook CancelManual  This step is unavailable to use in your environment. BackStep Name*                           Cannot be more than 140 characters.Only alphanumeric character, space and _ is allowed. &quot;Start&quot; step name already exists.+ Add Step DescriptionStep DescriptionMax 1024 character allowed.Trigger Button Label Execution Behaviour Requires record input to runRun Mode Run once for all selected records Run separately for each selected recordsChoose record modules on which the playbook would be available on × AlertsAnnouncementsAssetsAttachmentsCampaignsCommentCommunicationsCompaniesContent HubCredit CardsData ArchivalEmail TemplatesEventsFilesHuntsIncidentsIndicatorsQueuesRoutersShiftsSLA TemplatesSolution PacksTasksTenantsWar Rooms+ Configure Visibility ConditionsDisplay ConditionsDisplay the manual trigger only when the specified conditions are met.AlertsTrigger Condition:Select Logical OperatorALL OF THE BELOW ARE TRUE (AND)ANY OF THE BELOW IS TRUE (OR) ADD CONDITION  ADD CONDITIONS GROUPResulting Value:Select a valueTrueFalse                            Does not require a record input to runUser PromptInput PromptOpens a custom form on the playbook trigger to accept user input. Add FieldStep Utilities None addedLoop When Message Mock Output Variables   Message Save Cancel ')]</value>
      <webElementGuid>9c02b702-3541-47e5-b381-4be11df4f674</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
