<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Does not require a record input to run__81ecc9</name>
   <tag></tag>
   <elementGuidId>1e8843a4-0844-4607-be40-1c5944d8d291</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[name=&quot;resource&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e1a5394d-1aa0-4550-b521-588da064d651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-multi-select ui-select-container ui-select-multiple ui-select-bootstrap dropdown form-control ng-dirty ng-empty ng-invalid ng-invalid-required ng-touched</value>
      <webElementGuid>20932f46-6199-4af4-bd4d-8d2d99d5afa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{open: $select.open}</value>
      <webElementGuid>67ebb26d-a102-4e41-82d7-cf0811024b98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>resource</value>
      <webElementGuid>6153cde2-38fd-48fd-bae4-d15a3c480ca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>$parent.arguments.resources</value>
      <webElementGuid>bfc87518-158f-4adc-a7da-7a3c9f196138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>193793b7-b9ba-4fb2-82b8-849093c80cbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tagging</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>d8230aee-cae3-40c1-8fd1-a76a7d6f1cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tagging-label</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c6a4b7c3-616f-41b7-a8f7-be1d7ce73e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8c1aecd1-9531-45cc-9fa8-3ccfaca2a496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>67f9790f-e967-4d1c-893f-77558d4358db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step-form&quot;)/div[1]/form[@class=&quot;stepForm ng-valid-maxlength ng-valid-pattern ng-dirty ng-valid-parse ng-invalid ng-invalid-required&quot;]/fieldset[@class=&quot;selected-step-form-content&quot;]/div[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;ng-isolate-scope ng-not-empty ng-valid&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;execution-container&quot;]/div[@class=&quot;radio ng-scope&quot;]/div[@class=&quot;cs-radio-item margin-bottom-sm width-100pt&quot;]/div[@class=&quot;execution-content ng-scope&quot;]/div[@class=&quot;form-group padding-top-sm ng-scope has-error&quot;]/div[@class=&quot;cs-select&quot;]/div[@class=&quot;custom-multi-select ui-select-container ui-select-multiple ui-select-bootstrap dropdown form-control ng-dirty ng-empty ng-invalid ng-invalid-required ng-touched&quot;]</value>
      <webElementGuid>f32cce53-f1d0-423e-a100-a21d1aaa1166</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@name='resource']</value>
      <webElementGuid>0ef2ec46-0092-4d45-829b-1b88360ce9b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-form']/div/form/fieldset/div[5]/div/div/div/div[3]/div[2]/div/div/div/div/div</value>
      <webElementGuid>a629dee3-cd46-4335-a7b8-40baacf32c5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Prompt'])[1]/preceding::div[6]</value>
      <webElementGuid>423f8e15-ed3e-45c7-af14-fcb353cda867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Input Prompt'])[1]/preceding::div[6]</value>
      <webElementGuid>5db81eb9-b27c-4211-8922-4f8528fe3926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div/div</value>
      <webElementGuid>a1d4dd58-1d4e-409b-b59f-98b2f5e07552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@name = 'resource']</value>
      <webElementGuid>92ef8c71-0def-4936-96d7-265cca9ef7fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
