<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__stepName</name>
   <tag></tag>
   <elementGuidId>5c790168-39d0-4f1b-afb1-e135e88544a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#stepName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='stepName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>511d28bf-a7cb-4045-87c3-71710eea59b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>stepName</value>
      <webElementGuid>bed6eb4a-7897-4030-9abf-4bd95db45db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7bfeefbb-6387-46e5-ac22-721ce1d924e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-sm form-control ng-untouched ng-valid-pattern ng-valid-maxlength ng-not-empty ng-dirty ng-valid-parse ng-valid ng-valid-required</value>
      <webElementGuid>5cd1efaf-b480-42b0-aba1-e7d39ef181e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>stepName</value>
      <webElementGuid>505ae003-c249-4d84-9fa5-9af31ae78966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>stepSelected.name</value>
      <webElementGuid>1df0fe43-47de-4cda-88bf-a89ddb572e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-required</name>
      <type>Main</type>
      <value>stepSelected</value>
      <webElementGuid>28685494-d099-42e7-9c28-b5843ff40d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-pattern</name>
      <type>Main</type>
      <value>^[a-zA-Z0-9_ ]*$</value>
      <webElementGuid>3660196a-4d58-4b69-8bf4-76e2f30a4ea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-change</name>
      <type>Main</type>
      <value>clearDuplicateValidation(stepForm.stepName.$error.duplicate)</value>
      <webElementGuid>78bf4275-ca4b-4251-97ea-f742387391bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-maxlength</name>
      <type>Main</type>
      <value>140</value>
      <webElementGuid>37a2e8ef-ce0a-4a3a-9bb2-7aeeee182e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>01bfa9bb-dcd3-4454-a106-5e32b76c1956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>85483565-87fc-4f7d-9f8f-1618117a7f13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stepName&quot;)</value>
      <webElementGuid>62a644c7-a64e-4c6c-93ec-1d4240fd063c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='stepName']</value>
      <webElementGuid>8fe5982f-be44-4215-870e-1211d9c6d25c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-form']/div/form/fieldset/div[3]/input</value>
      <webElementGuid>3dda64ad-1786-485b-8b7e-71e09a8468b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[3]/input</value>
      <webElementGuid>2de85d16-da6c-469b-895e-5b78ecd56827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'stepName' and @type = 'text' and @name = 'stepName']</value>
      <webElementGuid>32aa3551-e02f-4c23-9c41-4d243ed4eab6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
