<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select an OptionAlertsAnnouncementsA_588099</name>
   <tag></tag>
   <elementGuidId>cb63fc20-b9be-41f4-a98d-9b206cc2ec1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#stepModel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='stepModel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f4db0ed1-8ecb-4def-bb3d-f55066d5c6c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>stepModel</value>
      <webElementGuid>334f4e0d-b5aa-4d53-b5ad-3d776a383392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm ng-pristine ng-empty ng-invalid ng-invalid-required ng-touched</value>
      <webElementGuid>a70005f9-2962-4a91-b8ac-9d04a645deb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>stepModel</value>
      <webElementGuid>7e20e36e-d072-420b-82d8-9ade68220227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-options</name>
      <type>Main</type>
      <value>module.typeIri as module.name for module in modules | playbookModules</value>
      <webElementGuid>17817825-e708-4f60-b718-eb83fe363f3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-change</name>
      <type>Main</type>
      <value>selectModule()</value>
      <webElementGuid>b44413cd-d3d8-4e73-809e-5cad0b9e1cd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>$parent.selectedModule</value>
      <webElementGuid>b2b6ad73-8d01-4677-bcc8-3f1956e1dcd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ec7a6976-aafd-481c-bfc5-330a114ecc97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select an OptionAlertsAnnouncementsAssetsAttachmentsCampaignsCommentCommunicationsCompaniesCredit CardsData ArchivalEmail TemplatesEventsFilesHuntsIncidentsIndicatorsQueuesRoutersShiftsSLA TemplatesSolution PacksTasksTenantsWar Rooms</value>
      <webElementGuid>3eaabe02-9d49-41ea-a422-e1c528ad60db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stepModel&quot;)</value>
      <webElementGuid>c1470a3c-4a9f-4b98-8b3f-157deedb46f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='stepModel']</value>
      <webElementGuid>10448986-9974-4b50-9850-da15bb3d1db1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-form']/div/form/fieldset/div[5]/div/div/select</value>
      <webElementGuid>156e6067-a68d-4d64-b3a8-2737ab0d3034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::select[1]</value>
      <webElementGuid>4be4f2f2-8fe9-4049-8943-54f31ac7304f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field is required.'])[1]/preceding::select[1]</value>
      <webElementGuid>26231f46-6f9d-4990-98bd-27469bb1347e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fields'])[1]/preceding::select[1]</value>
      <webElementGuid>7f2ffe4f-f891-4033-8112-c10cff9add7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>9a88fbfd-a6ad-421f-9bc1-410c3b9fd2ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'stepModel' and @name = 'stepModel' and (text() = 'Select an OptionAlertsAnnouncementsAssetsAttachmentsCampaignsCommentCommunicationsCompaniesCredit CardsData ArchivalEmail TemplatesEventsFilesHuntsIncidentsIndicatorsQueuesRoutersShiftsSLA TemplatesSolution PacksTasksTenantsWar Rooms' or . = 'Select an OptionAlertsAnnouncementsAssetsAttachmentsCampaignsCommentCommunicationsCompaniesCredit CardsData ArchivalEmail TemplatesEventsFilesHuntsIncidentsIndicatorsQueuesRoutersShiftsSLA TemplatesSolution PacksTasksTenantsWar Rooms')]</value>
      <webElementGuid>a3349684-6f1c-46bf-9572-71e95828e802</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
