<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Credit Cards_Credit Cards-Create</name>
   <tag></tag>
   <elementGuidId>4065c45b-33f0-4044-833d-6dcd454001a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>332fb002-bb90-47b7-b950-1cb58b96334f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Credit Cards-Create</value>
      <webElementGuid>f5a8d4f1-93e3-4a7f-ab3b-3d0260877d5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e6487814-8146-4a88-b755-98e343e5573c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>row.entity.canCreate</value>
      <webElementGuid>d98fa91b-73fa-4d8a-9ebe-5b8d1039589f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-disabled</name>
      <type>Main</type>
      <value>!grid.appScope.securityCanUpdate || row.entity.module.type === &quot;contentHub&quot;</value>
      <webElementGuid>45186b7c-9b23-4034-8657-4b86dca31b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-change</name>
      <type>Main</type>
      <value>grid.appScope.onChangePermission(row.entity, &quot;create&quot;)</value>
      <webElementGuid>de394941-abb7-4ab8-9c06-d65ac40224f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-valid ng-not-empty ng-touched</value>
      <webElementGuid>0a9dc61d-3be3-4a99-ac82-7b9ca3b965f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>24a1d15e-09fa-4242-b425-b0c9413402c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Credit Cards-Create&quot;)</value>
      <webElementGuid>4a745c6f-26d2-4b11-a4c2-2b1a19f67737</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Credit Cards-Create']</value>
      <webElementGuid>4eff27dd-6b39-4c3c-b2f9-bae80064ff92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1660735123434-15-uiGrid-010X-cell']/div/input</value>
      <webElementGuid>68be8737-0607-4e5b-88fe-629697e575ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/div/div[3]/div/input</value>
      <webElementGuid>fcee0fe6-c753-4c49-89cf-70ba61ca61ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Credit Cards-Create' and @type = 'checkbox']</value>
      <webElementGuid>66b07127-b768-4ae3-ac75-9f8689973175</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
