<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Alert Created By Automation Playbook</name>
   <tag></tag>
   <elementGuidId>3b44c40f-e4f9-43f5-9de7-1dc3e11d3af5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#view-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='view-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>fb3e77ca-1ffa-4c47-8206-f6e340a7d707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>view-name</value>
      <webElementGuid>46838695-101d-42ce-ae39-03c268782c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>field.type !== 'url'</value>
      <webElementGuid>5181c95f-c322-454d-a839-2977dbe0bc7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>word-break read-only-item margin-0 ng-binding ng-scope</value>
      <webElementGuid>cca4e627-3f1a-4a13-8635-3d88715cde59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Alert Created By Automation Playbook</value>
      <webElementGuid>2e383c3b-fb83-4027-ae32-44b24d4862a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-bind</name>
      <type>Main</type>
      <value>displayResult</value>
      <webElementGuid>0a85524b-b110-4828-bef1-9352ee5a5d94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{'filehash-field': field.type==='filehash'}</value>
      <webElementGuid>448b6870-466b-4c26-b729-7b884e7de062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alert Created By Automation Playbook</value>
      <webElementGuid>8e4ecad1-5cbe-4cef-a8dc-a9718fe88f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;view-name&quot;)</value>
      <webElementGuid>2d1feef0-8c8b-48b6-904d-691744d604f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='view-name']</value>
      <webElementGuid>5ed16d81-137c-4954-86b2-df8d2be93541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::p[1]</value>
      <webElementGuid>15d527e4-64b9-4039-82cc-00f8900086ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/following::p[1]</value>
      <webElementGuid>0fda9395-ed90-4fc6-ac36-97741da78ad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Modified 08/21/2022 08:18 AM by Playbook'])[1]/preceding::p[3]</value>
      <webElementGuid>8172d4e9-4590-403d-98b1-29c7c6dcbd09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tags'])[1]/preceding::p[3]</value>
      <webElementGuid>c92e432e-4a79-414a-b09e-cde1638e0f41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Alert Created By Automation Playbook']/parent::*</value>
      <webElementGuid>3447ad21-a2ba-47ad-a866-564d8c9f2185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ng-form/div/div/div/div/p</value>
      <webElementGuid>7b570378-3d86-46ae-b920-e027d5454e54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'view-name' and @title = 'Alert Created By Automation Playbook' and (text() = 'Alert Created By Automation Playbook' or . = 'Alert Created By Automation Playbook')]</value>
      <webElementGuid>dee6af4f-32ec-4317-9526-a6813c919760</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
