<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_High</name>
   <tag></tag>
   <elementGuidId>5a823b98-73c7-4d27-8aaf-51a2803d9dbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.text.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='editable-severity-lookup-btn']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3a04f222-80c1-49bc-a4dc-9e1fd9a15a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text ng-binding</value>
      <webElementGuid>40f5f8f6-e778-4b01-a26b-8a15a3c4fc4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>High</value>
      <webElementGuid>86ec506e-071f-4a41-ae1f-95db62b782d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editable-severity-lookup-btn&quot;)/div[1]/span[@class=&quot;text ng-binding&quot;]</value>
      <webElementGuid>2a92d63b-6459-4489-b139-7b778b851179</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='editable-severity-lookup-btn']/div/span</value>
      <webElementGuid>987b5c4a-261c-459f-b6ef-e77f5c17dae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Severity'])[1]/following::span[3]</value>
      <webElementGuid>67a38914-2ec2-4a7d-9b03-c582c645e345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alert: Alert Created By Automation Playbook'])[1]/following::span[4]</value>
      <webElementGuid>5cabe450-133c-4305-8efe-a128e8ef16b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='{}'])[1]/preceding::span[2]</value>
      <webElementGuid>0bf58c5c-ca0b-4365-b922-96553c0f5969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='High'])[2]/preceding::span[3]</value>
      <webElementGuid>d7608dc9-ed68-48f7-8c48-55bc18461df1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='High']/parent::*</value>
      <webElementGuid>de69bb3f-0494-4599-8596-a98d6ee6ac35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/span</value>
      <webElementGuid>87252fe4-52eb-45fe-a43d-e98519f57cf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'High' or . = 'High')]</value>
      <webElementGuid>2331a093-d3e2-4ce9-bbd6-348dcebb6183</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
