<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add</name>
   <tag></tag>
   <elementGuidId>f71a13ab-d8b2-4dcf-8430-669b134dcfe5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='add-credit card-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e25c6e92-fbdb-40a5-817f-31e4bce20f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-credit card-btn</value>
      <webElementGuid>20f9a45f-da59-45df-a272-cd97f24e8891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add Credit Card</value>
      <webElementGuid>d21ac3bb-c8f0-4cfd-8c74-58fa01829d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-hide</name>
      <type>Main</type>
      <value>gridOptions.csOptions.enableSelectMenu &amp;&amp; !gridOptions.csOptions.allowAddRelations &amp;&amp; getSelectedCount() > 0</value>
      <webElementGuid>e86001ea-f180-415f-b643-b7b1abba7626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-action btn btn-sm cs-btn btn-primary margin-left-negative-3 ng-binding ng-scope</value>
      <webElementGuid>fafd61a9-38b6-4636-a282-61ed85f5d207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f6f1de5a-941a-4cba-95be-48ec61bedfb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>gridOptions.csOptions.onAdd()</value>
      <webElementGuid>bd896af5-aca7-4731-9dad-db5463a2586b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-if</name>
      <type>Main</type>
      <value>gridOptions.csOptions.allowAdd || gridOptions.csOptions.allowAddRelations</value>
      <webElementGuid>8515a05f-d119-4740-b977-5e6624e0b54d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e8fe9685-5e30-43c0-93ca-f59ae76d2b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>94edf134-fb93-4e33-b309-e97a70a988a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-credit card-btn&quot;)</value>
      <webElementGuid>96e18926-c276-4eba-88b0-e420b2267174</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='add-credit card-btn']</value>
      <webElementGuid>62666df9-dfc0-403d-a168-dab097c77190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-view-template']/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div/div/div/div[3]/div/div/button[2]</value>
      <webElementGuid>ecc7ecf4-0616-4b7f-81d5-9039e0bd4c42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Cards'])[3]/following::button[3]</value>
      <webElementGuid>c1a12519-e8ae-4ef8-8e2b-05dc5ae1347d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not applicable'])[5]/following::button[3]</value>
      <webElementGuid>16984f26-7c34-402c-8fa5-c1c94cdec134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save Filter'])[1]/preceding::button[7]</value>
      <webElementGuid>64341a41-4a0b-4295-b490-1ea4d5c663f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Query Save Options'])[1]/preceding::button[8]</value>
      <webElementGuid>1ce0153d-ef42-4336-b5ac-ca57fc8f4e56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add']/parent::*</value>
      <webElementGuid>d978e587-9d5f-4c75-bc54-98c7f719c7da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button[2]</value>
      <webElementGuid>50830b92-41fe-4118-87e9-9e8b1e8c0069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'add-credit card-btn' and @title = 'Add Credit Card' and @type = 'button' and (text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>edcdccd0-07d7-4ca8-b3e1-f32a2481aaf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
