<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>8a342ce5-0545-4490-9f73-6cc0293b11b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#breadcrumb-add</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='breadcrumb-add']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f0e48cf2-409c-4ede-a77e-b1548908309e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>breadcrumb-add</value>
      <webElementGuid>45e6c119-2c4b-457b-b5a5-29b5fbf094f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c864f67f-aa2b-4d6d-a915-8d89748257eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>save()</value>
      <webElementGuid>2fd5e4b7-13ca-4f0c-943d-b96882bc310d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-primary margin-right-negative-2</value>
      <webElementGuid>7a59e965-0a7d-4f4c-8e54-073c97fd77ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-disabled</name>
      <type>Main</type>
      <value>processing</value>
      <webElementGuid>eba150f6-0912-4b46-9e4b-8531360eea2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-show</name>
      <type>Main</type>
      <value>mode === 'add' &amp;&amp; permission.create || mode === 'edit' &amp;&amp; permission.update</value>
      <webElementGuid>e7277b3a-56c7-47ed-b3ab-d43233c2b53a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ab4b7feb-741f-4b1f-9628-99d4ac637a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Save</value>
      <webElementGuid>6f29b79a-ed0e-4a34-a9bf-2881dff30358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;breadcrumb-add&quot;)</value>
      <webElementGuid>a2678f59-5f23-4993-80fe-b0dcb80239b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='breadcrumb-add']</value>
      <webElementGuid>562c182e-8bff-44e3-8c31-fd8ec072f89d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-view-template']/div/div/form/div/div[2]/div/div/div/button</value>
      <webElementGuid>8fe65849-a231-4f91-a6bc-41b01bc0fe4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[22]/preceding::button[1]</value>
      <webElementGuid>c8bf5d9a-580d-4114-a8c7-eeec19010445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>f09094e2-f1e7-46c4-bfc9-44ca9d6342d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button</value>
      <webElementGuid>0430e135-aa97-49a1-bc2f-67ef85cac3eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'breadcrumb-add' and @type = 'button' and (text() = ' Save' or . = ' Save')]</value>
      <webElementGuid>d6c6b1e8-15b4-415b-bcc9-a867e0a43ec2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
