<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Reset Password</name>
   <tag></tag>
   <elementGuidId>dd1d63d2-bdec-43b2-93a0-d53eaaddbc47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reset-password-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='reset-password-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8a740cb8-bcbe-42ca-a857-46bc1822c6d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reset-password-btn</value>
      <webElementGuid>1590d636-b5db-4633-ae6b-2be5b2fa7eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-default margin-top-2 ng-scope</value>
      <webElementGuid>9e41074d-788b-4c7a-b7e4-7677c85f4810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>959614ea-ddbf-4f41-8a03-62a21657b7cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-if</name>
      <type>Main</type>
      <value>securityCanUpdate===true</value>
      <webElementGuid>037d93d7-b89d-40a9-bf80-ebb722629e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-show</name>
      <type>Main</type>
      <value>fields.userId.value &amp;&amp; !isCurrentUser &amp;&amp; !user.credentials.bind_name.value</value>
      <webElementGuid>bc270d3f-6768-4a98-9713-a6630bb4e1af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>resetPassword(true)</value>
      <webElementGuid>d141f0fe-64ed-4e82-9931-d16621142e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-disabled</name>
      <type>Main</type>
      <value>resetPasswordDisabled</value>
      <webElementGuid>9f6eba87-8d86-4b2c-ba2f-39b4642f276b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a2bfdbb9-b52c-4b60-a2b3-41a4c633b9c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reset Password</value>
      <webElementGuid>6dbd961f-44f2-4d55-be1c-8ce1eb791ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reset-password-btn&quot;)</value>
      <webElementGuid>bc8de300-8370-4add-b9b9-764f2cefb990</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='reset-password-btn']</value>
      <webElementGuid>cc4b3f96-4afa-4981-ba74-56cabc9e4015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='admin-pane']/div/div/div/form/div[3]/div[2]/div[3]/div[2]/div/div/div[2]/button</value>
      <webElementGuid>6ea47d4a-a678-4490-9887-cc92a292a59f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::button[1]</value>
      <webElementGuid>40fd5504-549a-4fcc-a3a4-becec38def2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Access Type'])[1]/preceding::button[1]</value>
      <webElementGuid>e6c6861c-096b-4532-ab65-ea77f3eb883e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reset Password']/parent::*</value>
      <webElementGuid>4fa003eb-113e-4997-8f88-81c4806a521f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/button</value>
      <webElementGuid>baedd9e3-6018-43ad-8a73-6fc8234a4161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'reset-password-btn' and @type = 'button' and (text() = 'Reset Password' or . = 'Reset Password')]</value>
      <webElementGuid>8ad08d59-0c84-4776-9eb8-604a8cac1642</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
