<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_UserB One_userpic margin-top-2</name>
   <tag></tag>
   <elementGuidId>21165e9b-3f8c-4aee-914a-5d81efe05af2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.userpic.margin-top-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='user-links']/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6a6ef781-b50a-4936-af46-1f3a45b2e49b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>userpic margin-top-2</value>
      <webElementGuid>adcbbe76-aab8-4a3d-a3df-f4dcd8d2a79f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>uib-tooltip</name>
      <type>Main</type>
      <value>CS Admin</value>
      <webElementGuid>98e34441-6143-4834-92a6-34d8a810c0a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-placement</name>
      <type>Main</type>
      <value>bottom</value>
      <webElementGuid>752d05f5-bacc-4f3a-8bd8-96cbebabc883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-src</name>
      <type>Main</type>
      <value>images/default-profile-photo.png?v=1</value>
      <webElementGuid>f9ae544d-fca1-4ede-899c-84fa589e1177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/default-profile-photo.png?v=1</value>
      <webElementGuid>045cb025-b6f5-46b6-a88d-cfdc0a322aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user-links&quot;)/span[@class=&quot;no-border padding-0 padding-left-md padding-right-md&quot;]/img[@class=&quot;userpic margin-top-2&quot;]</value>
      <webElementGuid>cec61c97-30bf-4ad9-89c1-3d8bb7cd741e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='user-links']/span/img</value>
      <webElementGuid>0b6f1aa3-2f41-4dfe-8230-33d94778e03e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>a35c3a83-8f85-45af-94c1-9032d0e1da9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/default-profile-photo.png?v=1']</value>
      <webElementGuid>9c282262-ef50-4210-bf14-50d8246dd522</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
