<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__confirmPassword</name>
   <tag></tag>
   <elementGuidId>10b2382d-0e79-44c7-be33-56819dab1888</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;confirmPassword&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='confirmPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cbb0c48d-1085-4a63-98a6-d4d7166c25c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c9bc81bd-b83d-459a-856e-5315fcc56f79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>ed970e5e-7bf1-4aa8-a36d-114e9ceeed09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirmPassword</value>
      <webElementGuid>4536b3bf-915d-4c08-9ca6-198e14494483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>confirmPassword</value>
      <webElementGuid>a30eb17d-2fcc-416c-b18c-c22883151bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-isolate-scope ng-invalid ng-invalid-compare-to ng-not-empty ng-dirty ng-valid-parse ng-valid-required</value>
      <webElementGuid>b09df8bd-53ec-443d-9d4e-6e8b738ca83d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cs-compare-to</name>
      <type>Main</type>
      <value>newPassword</value>
      <webElementGuid>7487e1fa-68a4-4116-9c9c-0e3c17c0a9b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>ee43cf52-ee6c-47e0-8d7c-88ec7db990f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>944da335-dca4-4c63-a863-2d92a12f9f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[@class=&quot;animated fadeIn modal-open&quot;]/div[@class=&quot;modal modal-password fade ng-scope ng-isolate-scope in&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/form[@class=&quot;ng-scope ng-invalid ng-dirty ng-invalid-compare-to ng-valid-parse ng-valid-required&quot;]/div[@class=&quot;modal-body version-border margin-top-md padding-top-sm&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;form-group margin-bottom-0 margin-bottom-sm&quot;]/div[@class=&quot;col-sm-8&quot;]/input[@class=&quot;form-control ng-untouched ng-isolate-scope ng-invalid ng-invalid-compare-to ng-not-empty ng-dirty ng-valid-parse ng-valid-required&quot;]</value>
      <webElementGuid>379e9b47-b606-4799-95f1-b7b71b29e244</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='confirmPassword']</value>
      <webElementGuid>e796bb6a-7c73-44af-88d1-fe9c0954141f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>a94b9ad8-3518-4a93-a51f-2e917e21e1e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'confirmPassword']</value>
      <webElementGuid>dc77cb75-a158-4c8b-ba6e-af5d569132a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
