<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add To Menu</name>
   <tag></tag>
   <elementGuidId>71b10f25-e45c-40d2-877c-a8d6ebba7a5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add-module-as-group</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='add-module-as-group']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a99a459f-f46e-4469-9c76-732bbdc182c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-module-as-group</value>
      <webElementGuid>b964ef78-74d5-4fa0-88df-860ee4d9d3de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-default margin-top-sm</value>
      <webElementGuid>11028269-5f3c-4719-b76b-baef49176166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-disabled</name>
      <type>Main</type>
      <value>!modulesSelected</value>
      <webElementGuid>f9bed86f-e19e-4e57-bc5f-b9965fc63c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>addToMenu('modules')</value>
      <webElementGuid>07e47d57-4144-46a4-8e9a-4ad51044174b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add To Menu</value>
      <webElementGuid>ee786413-023c-4cca-90ad-bfc9918fc409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;admin-pane&quot;)/div[@class=&quot;admin-content ng-scope&quot;]/div[@class=&quot;padding-left-xlg padding-right-xlg padding-bottom-xlg clearfix ng-scope&quot;]/div[@class=&quot;row padding-bottom-xlg&quot;]/div[@class=&quot;col-lg-3&quot;]/div[@class=&quot;panel-body panel-default solid-border ng-isolate-scope&quot;]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;tab-pane ng-scope active&quot;]/div[@class=&quot;padding-top-md padding-bottom-md ng-scope&quot;]/div[@class=&quot;solid-border-top padding-top-md&quot;]/button[@id=&quot;add-module-as-group&quot;]</value>
      <webElementGuid>f447f244-c2fb-4fdd-9f2b-1377fa04aa15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='add-module-as-group']</value>
      <webElementGuid>13598deb-1e7a-4918-b6ec-1d44e7af4eb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='admin-pane']/div/div/div[3]/div/div/div/div/div/div[2]/button[2]</value>
      <webElementGuid>70924449-815f-4974-96fe-baaa0f5d614a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add As Group'])[1]/following::button[1]</value>
      <webElementGuid>64b21b06-ca07-45c4-b642-28cddda29471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add To Menu']/parent::*</value>
      <webElementGuid>3db85da4-3dd0-4520-a4f8-f8085fe48e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div[2]/button[2]</value>
      <webElementGuid>0af4b7f3-d6c3-4780-9491-5e725b3b0e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'add-module-as-group' and (text() = 'Add To Menu' or . = 'Add To Menu')]</value>
      <webElementGuid>dd444312-aa94-4bc0-8811-aa3dcfffa830</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
