<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Credit Cards_edit-name-10</name>
   <tag></tag>
   <elementGuidId>a9941d2b-954b-424d-998a-91eded40fba9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-name-10</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='edit-name-10']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c6bf6234-481f-4bc3-9659-98d5f333c610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>19415584-1292-4bba-9908-ef79f8c365df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-transparent btn-xs</value>
      <webElementGuid>02c763ed-8b1b-4686-8131-9043abd01ab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-name-10</value>
      <webElementGuid>b0385026-15fe-4d92-b15c-430cea7250dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>enableEdit($index)</value>
      <webElementGuid>8e891dde-7da0-436a-aa29-20e8449d5507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Edit Name</value>
      <webElementGuid>12246662-10bf-4e6a-8a62-9d692835687d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-name-10&quot;)</value>
      <webElementGuid>9b014a71-526e-40a3-ab31-560acee7d078</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='edit-name-10']</value>
      <webElementGuid>f376bd17-56dd-429c-adbe-2c324656bcad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navigation-list']/ul/li[11]/div/div/div[2]/div/button</value>
      <webElementGuid>4aa7b474-4af4-42a2-8b3b-68cfee01db74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Cards'])[1]/following::button[1]</value>
      <webElementGuid>f6c1f237-ac83-4dbe-a0a5-582dcbbc83a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Community'])[2]/following::button[5]</value>
      <webElementGuid>9735a31b-f5a3-4cec-99b8-3f827fdea5fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'edit-name-10', '&quot;', ')')])[1]/preceding::button[4]</value>
      <webElementGuid>3be1ee27-53e1-4dc9-a35f-de24da5fad5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]/div/div/div[2]/div/button</value>
      <webElementGuid>79effdc8-2827-4c2d-85c1-b01761fd7fd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'edit-name-10' and @title = 'Edit Name']</value>
      <webElementGuid>0fc4309a-5d58-4c9d-81cb-af63d8e98f4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
