<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>d869bc63-71cd-4269-b0ff-7ecf6017548f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#navigation-actions-save</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='navigation-actions-save']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2290ca8a-a7bc-443c-87b5-4b75368dac28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>navigation-actions-save</value>
      <webElementGuid>95cc2c79-d552-4969-963c-92ff8a62262e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm margin-right-negative-2 padding-right-lg</value>
      <webElementGuid>9b745a17-94e4-48cf-8bfe-b1c5129f547b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9586aebb-3ad5-4c61-aa6e-4e02bfe8f508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>save()</value>
      <webElementGuid>2c93eaf9-f45f-40d1-a10f-8f01006c2d81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-disabled</name>
      <type>Main</type>
      <value>!isDirty || processing</value>
      <webElementGuid>226b7858-9eb1-42d1-8d6a-6c531f8e2561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>f5200f76-4e04-4bb7-a2d2-7751566145dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navigation-actions-save&quot;)</value>
      <webElementGuid>d2e6536b-0060-4d7a-874a-b9c136298fee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='navigation-actions-save']</value>
      <webElementGuid>23d7cdb7-c975-4779-a256-da5d8dc4913e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='admin-pane']/div/div/div[2]/button</value>
      <webElementGuid>0ac2f823-475f-4f6a-aeea-000edca040da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Navigation'])[2]/following::button[1]</value>
      <webElementGuid>eea5520f-d4ce-43bd-87ff-698485826313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Import Wizard'])[1]/following::button[1]</value>
      <webElementGuid>788567fc-6228-4227-8135-b8d72be08aa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Revert'])[1]/preceding::button[1]</value>
      <webElementGuid>1ce0fdb0-1e61-4132-bbae-e6c575451b56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modules'])[2]/preceding::button[2]</value>
      <webElementGuid>ff388c4a-7e5a-4bc9-a39b-e96b8c20e609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>3bf4e01b-2f2b-473c-b9bd-9c95092c6b28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/button</value>
      <webElementGuid>312fb4b4-933a-47cf-8c8d-8c0eeb456ba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'navigation-actions-save' and @type = 'button' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>a7dfcfb3-5f2b-4975-993a-9740e52bfe4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
