<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Credit Cards_modules-credit_cards</name>
   <tag></tag>
   <elementGuidId>8162adda-c5d7-4091-9478-285444d0024c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modules-credit_cards</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='modules-credit_cards']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>21418f64-d64c-42a2-836f-90bc0b56d523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>68dc31f0-c120-4ad3-be6f-587611dc1cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modules-credit_cards</value>
      <webElementGuid>27345fff-0780-43b6-bd10-ccc19cca37d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>modules-credit_cards</value>
      <webElementGuid>b4d72e14-abf0-44f0-b02a-ee151758cab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-change</name>
      <type>Main</type>
      <value>setSelected(module.selected, 'modules')</value>
      <webElementGuid>01fcfe4c-7a8b-41ff-ba76-67ea80fbeabc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>module.selected</value>
      <webElementGuid>d6d2c2d7-d4a6-4250-9b06-3f15c3471ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>89141fed-2a85-48f0-97af-5d6d99d56566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c7138998-f745-4c25-9b08-d8ca6ec6cb87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modules-credit_cards&quot;)</value>
      <webElementGuid>3f8a5c8c-4e73-46c2-ad15-7b9e864f3200</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='modules-credit_cards']</value>
      <webElementGuid>9a5d82e0-1d71-47d9-b4f5-29aea5f927df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='admin-pane']/div/div/div[3]/div/div/div/div/div/div/div[16]/label/input</value>
      <webElementGuid>81025727-62f7-4a86-b0d5-04ebd73e2288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/label/input</value>
      <webElementGuid>49788562-8d57-4ed7-a8e8-671175f6d38d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'modules-credit_cards' and @name = 'modules-credit_cards']</value>
      <webElementGuid>6169202b-580a-4f6d-97bf-f991d4443d88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
