<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_New Collection</name>
   <tag></tag>
   <elementGuidId>516630e9-9520-4c3b-aa87-70549c8fae80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-newCollection</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-newCollection']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6b5f6766-3d9c-424e-aade-f6244d359c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-newCollection</value>
      <webElementGuid>5d8da101-b855-45e2-9766-c43d3241c668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm</value>
      <webElementGuid>046ba023-f90d-41fa-b26d-f826333c360b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-show</name>
      <type>Main</type>
      <value>permission.create</value>
      <webElementGuid>a97d20a3-342c-440f-b1a0-ffa3ff897e5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>newCollection()</value>
      <webElementGuid>ad334b4b-6b65-487f-9359-d1976cac8634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cfd808a8-3909-437d-9e21-27ec870986b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  New Collection</value>
      <webElementGuid>df8718f2-c8b6-4f3c-a209-f2132949b0a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-newCollection&quot;)</value>
      <webElementGuid>f874a9e9-19fc-4c53-960a-7f7a9f60822b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-newCollection']</value>
      <webElementGuid>dff843f9-0952-488d-a69f-f96a5bd68ef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list-items']/div/div/div/button[2]</value>
      <webElementGuid>c859d7ac-d381-4cfc-9cd3-5bf223fa80de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collections'])[2]/following::button[3]</value>
      <webElementGuid>3c127726-84fe-47c3-afc3-ffca134b91bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Playbooks'])[4]/following::button[3]</value>
      <webElementGuid>2f0a56de-fdaf-4c6a-954f-d59f49d8cdce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Include System Collections'])[1]/preceding::button[2]</value>
      <webElementGuid>d1ba5788-6547-4534-bbf8-a3fa9ececffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/button[2]</value>
      <webElementGuid>d356fa21-8094-435e-ac55-36198ad8067a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-newCollection' and (text() = '  New Collection' or . = '  New Collection')]</value>
      <webElementGuid>7a4fdce7-a66d-4ffc-85fd-d0aac7ec1b10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
