<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Create</name>
   <tag></tag>
   <elementGuidId>941c3ba4-1ae6-4d90-9657-7e02c836f5ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#submit-add-modal-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='submit-add-modal-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>560a7805-4a2c-44e1-941e-5235ffff82ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>7b791e1d-47f4-4f06-89e6-3618d5176453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-primary margin-right-negative-2 ng-binding</value>
      <webElementGuid>4d573776-0cc9-46fb-81f4-f5af2abdb546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-bind</name>
      <type>Main</type>
      <value>submitDisplay</value>
      <webElementGuid>d07f0c9a-3659-4459-bc88-c5124f317bad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-disabled</name>
      <type>Main</type>
      <value>processing || newForm.$invalid</value>
      <webElementGuid>cfa4e60f-daa3-4df4-9e75-76b0c3cb9df4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submit-add-modal-btn</value>
      <webElementGuid>d8bcd713-cde5-429d-8f67-891a6701be00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create</value>
      <webElementGuid>b4b7fece-dd27-4a0a-992b-e52dfb5c87a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submit-add-modal-btn&quot;)</value>
      <webElementGuid>ac0bfa97-31d1-49b8-a2d5-d04d0d50730d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='submit-add-modal-btn']</value>
      <webElementGuid>56e80b44-aed7-454a-849b-6861a1cffb77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='newForm']/div[3]/button</value>
      <webElementGuid>0b45bbe7-a173-4136-8aa5-484b27e0078c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link Team'])[1]/following::button[1]</value>
      <webElementGuid>a3b4afac-dc37-4d78-9c64-8637088a4a80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Owners'])[1]/following::button[2]</value>
      <webElementGuid>1f751c8f-b5fb-4a6f-b649-5d6a0fe8c67c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[1]</value>
      <webElementGuid>5a4719bf-c4ac-4ac3-8365-69ff391f443d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle Navigation'])[1]/preceding::button[2]</value>
      <webElementGuid>21c633c2-07e5-4a54-874b-9fd7b4a82a98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create']/parent::*</value>
      <webElementGuid>6f8f39b3-54b5-40fc-89e1-3642ec3eab81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>6a2be5a2-792d-4aad-a94a-72b598b7343a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'submit-add-modal-btn' and (text() = 'Create' or . = 'Create')]</value>
      <webElementGuid>dbce42e2-de67-4e19-8af0-60379f0b9424</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
