<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Alerts</name>
   <tag></tag>
   <elementGuidId>1167c8fe-c25f-4d45-88de-7240f350e05c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.new-truncate-ellipsis.ng-scope > a.ng-binding.ng-scope</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navigation-wrapper']/div[2]/div/nav/ul/li[3]/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>82733244-7838-47d9-b1f6-964bfc186b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-if</name>
      <type>Main</type>
      <value>!item.openInNewTab</value>
      <webElementGuid>d855c39b-6d07-40e3-b395-554755cf09e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui-sref</name>
      <type>Main</type>
      <value>main.modules.list({&quot;module&quot;:&quot;alerts&quot;})</value>
      <webElementGuid>38ffd0d0-9046-4864-9c22-0c8b0ef6bf0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ui-sref-opts</name>
      <type>Main</type>
      <value>{inherit: false}</value>
      <webElementGuid>becdecdf-821e-41dc-bffb-ab20147dc9e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Alerts</value>
      <webElementGuid>4efc357e-3f6d-47dc-be56-39d6123160d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding ng-scope</value>
      <webElementGuid>656912f7-1f49-4661-8229-7a91afdfc492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/modules/alerts</value>
      <webElementGuid>0e438469-17c2-47e5-9b6e-d3cc970f941b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alerts</value>
      <webElementGuid>e83deef7-9d4b-4e2e-a501-45c89cef9fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navigation-wrapper&quot;)/div[@class=&quot;nav-top-bar navigationHeight nav-full-width&quot;]/div[@class=&quot;slim-scroll-wrapper&quot;]/nav[@class=&quot;mini-nav ng-scope&quot;]/ul[@class=&quot;navigation&quot;]/li[@class=&quot;animate-show-hide ng-scope&quot;]/ul[@class=&quot;animate-show-hide ng-scope ng-hide&quot;]/li[@class=&quot;new-truncate-ellipsis ng-scope&quot;]/a[@class=&quot;ng-binding ng-scope&quot;]</value>
      <webElementGuid>2a0f2da3-eea1-471e-b1df-e0274737261b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navigation-wrapper']/div[2]/div/nav/ul/li[3]/ul/li[2]/a</value>
      <webElementGuid>1de68950-926d-4ddd-8ff2-c93d6a97b8c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Alerts')]</value>
      <webElementGuid>3ddb6b6c-bf36-48fb-a8ec-5509bdecebef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incident Response'])[1]/following::a[1]</value>
      <webElementGuid>4c811e5a-8321-41b6-a761-557ff2e63cdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Queue &amp; Shift Management'])[1]/following::a[3]</value>
      <webElementGuid>d95629fd-6d07-4b23-8b8a-7a39e84bfad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incidents'])[1]/preceding::a[1]</value>
      <webElementGuid>3973c28c-c89d-4c6c-9132-bcb9b6f4c85b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tasks'])[1]/preceding::a[2]</value>
      <webElementGuid>03bfa9c4-5c1a-48af-a312-cd66d6e7786d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Alerts']/parent::*</value>
      <webElementGuid>672f9590-57e1-49e3-a1a8-9d25d44cce83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/modules/alerts')]</value>
      <webElementGuid>a0602be1-83ce-483e-9d21-ef833b0b8743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li[2]/a</value>
      <webElementGuid>4e1fd5db-de20-41b3-b91e-13960e448586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Alerts' and @href = '/modules/alerts' and (text() = 'Alerts' or . = 'Alerts')]</value>
      <webElementGuid>f2e8a4fe-6da1-465c-bdcf-604618e05273</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
