<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Severity</name>
   <tag></tag>
   <elementGuidId>c37f8fac-88b1-490f-9d84-e5b6b3b4ad87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.primary-div.ng-scope > a.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Severity')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fadf8b8a-d886-44b9-9f4a-103911c52ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>c5c1a42e-b820-4933-a4e0-b946c425bc16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>conditionSet.module=field.name; primaryFieldChanged($parent.$index,fields);</value>
      <webElementGuid>446424f3-e144-4b7f-b570-0f1a6841086d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>4bbc2ac6-ff17-4ab4-b459-8151c359b9ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Severity</value>
      <webElementGuid>209be7ee-cc59-4b6d-b1e6-43346c94a8c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[@class=&quot;animated fadeIn modal-open&quot;]/div[@class=&quot;modal modal-ingestion ng-scope ng-isolate-scope in&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/queue-wizard[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;modal-body padding-0 queue-wizard&quot;]/div[@class=&quot;cs-wizard ingestion-steps queue-wizard-steps ng-isolate-scope&quot;]/div[@class=&quot;steps ng-scope&quot;]/section[@class=&quot;ingestion-modal-padding wz-reviewoptions-step step ng-scope ng-isolate-scope current&quot;]/form[@class=&quot;ng-scope ng-dirty ng-valid-parse ng-invalid ng-invalid-required&quot;]/div[@class=&quot;full-width wz-step-height&quot;]/div[@class=&quot;row wizard-full-height margin-0&quot;]/div[@class=&quot;col-md-8 padding-bottom-65 padding-top-40 padding-left-45 padding-right-53 wizard-full-height overflow-auto&quot;]/div[@class=&quot;padding-top-md ng-scope&quot;]/div[@class=&quot;dashed-border-section ng-scope&quot;]/div[@class=&quot;padding-lg top-border&quot;]/div[@class=&quot;form-group margin-bottom-lg ng-scope&quot;]/div[@class=&quot;ng-pristine ng-untouched ng-valid ng-isolate-scope ng-not-empty&quot;]/div[@class=&quot;condition-group ng-scope&quot;]/div[@class=&quot;margin-left-sm and&quot;]/div[@class=&quot;condition-div ng-scope&quot;]/div[@class=&quot;row margin-bottom-sm conditions-row ng-scope&quot;]/div[@class=&quot;col-md-4 padding-right-0&quot;]/div[@class=&quot;form-group margin-bottom-0&quot;]/div[@class=&quot;btn-group cd-dropdown dropdown open&quot;]/ul[@class=&quot;dropdown-menu&quot;]/li[@class=&quot;primary-div ng-scope&quot;]/a[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>71eeedef-8366-49f1-8ada-e5cff12b88b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Severity')]</value>
      <webElementGuid>a40511fa-df15-4f0c-9401-9e5bd0d009b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PRIMARY FIELDS'])[1]/following::a[1]</value>
      <webElementGuid>a83f35d6-e599-4fd6-a914-12305e0d14fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a field'])[1]/following::a[1]</value>
      <webElementGuid>65a894ee-fb79-4218-9e3a-5f822e1a996b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Severity']/parent::*</value>
      <webElementGuid>41c4824c-4628-4349-8b7d-aa59f92e846f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>e3eea554-9226-48c9-9121-a95b824d0ee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/ul/li[2]/a</value>
      <webElementGuid>526f752b-30e4-4065-a0c0-aa89a6015c89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Severity' or . = 'Severity')]</value>
      <webElementGuid>b4e067a4-559c-48e3-9145-3524c434fe7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
