<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Select a field</name>
   <tag></tag>
   <elementGuidId>033da3a6-16bc-4a28-99e6-b15796f1f534</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select-conditional-field-0-queueRules</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='select-conditional-field-0-queueRules']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0b3f2dbc-8429-448b-9ac2-0be3726bfe65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm ng-binding dropdown-toggle</value>
      <webElementGuid>0377e5e9-b3c5-4c12-8e7e-65633505ae75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>b1636f02-b69b-4ce8-ac81-9df82d54067f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d0cb6d77-a0b5-45ec-bc95-a1027aa7358c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>8c022b07-f3c7-4d0b-a057-b9e663b3cda0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>23a46fc5-694e-4868-b659-b98c30bd5838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select-conditional-field-0-queueRules</value>
      <webElementGuid>70ca5c38-b4b5-4018-ad3d-4f3165e20aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Select a field</value>
      <webElementGuid>63568b31-c1ee-4ecb-ba15-a5a8e2b452a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>59ff6d19-2508-42b5-8df9-5c5baa203eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1e96fd0e-59ad-4847-9e83-a38cfd49103d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>29c3a0e5-4186-46e3-b3e9-fd5780c9faf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select a field </value>
      <webElementGuid>86ce33c1-dc6c-4139-a49a-ca41bdc04845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-conditional-field-0-queueRules&quot;)</value>
      <webElementGuid>66f55abe-e99a-44ee-ac96-8c3a15c789ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='select-conditional-field-0-queueRules']</value>
      <webElementGuid>7d9f0ec9-fad5-4e74-8da4-03a209c0566e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rule Name'])[1]/following::button[1]</value>
      <webElementGuid>cf525459-3f0a-4758-9e8c-6a725c7d218e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PRIMARY FIELDS'])[1]/preceding::button[2]</value>
      <webElementGuid>be66e811-3257-4e61-9184-ec3ebda6218b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select a field']/parent::*</value>
      <webElementGuid>efb1a375-2217-4132-be96-c8127498e5ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div/div/div/button</value>
      <webElementGuid>8f33ee00-ac90-4f28-824e-389600b0a54c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'select-conditional-field-0-queueRules' and @title = 'Select a field' and (text() = 'Select a field ' or . = 'Select a field ')]</value>
      <webElementGuid>7c31a690-e8bb-4abd-b4ca-b79d15e9dca4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
