<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next Define Rules</name>
   <tag></tag>
   <elementGuidId>e8a7961a-1741-4f52-8ada-dfa2d2655b34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#queue-wizard-move-to-members-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='queue-wizard-move-to-members-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8bb72f4b-f34a-44c7-af9e-6d0a8e00596b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>20f2bd4e-6bec-42ca-bc94-df4088f5b353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary pull-right btn-sm margin-top-lg margin-right-lg</value>
      <webElementGuid>2c9b864b-4c9b-46fb-808e-198a0ddeef83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>queue-wizard-move-to-members-btn</value>
      <webElementGuid>87d0e435-31dd-4a42-b525-20f62f8cce43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>$ctrl.nextPageLoading</value>
      <webElementGuid>037ca39a-7b39-47fc-b46e-a4e50cbb8e75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next: Define Rules</value>
      <webElementGuid>54950a0a-78f6-4ba1-a5be-0dcb9341261c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;queue-wizard-move-to-members-btn&quot;)</value>
      <webElementGuid>51331cbb-a5fb-4dbb-a7a3-4fa4feac0ac7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='queue-wizard-move-to-members-btn']</value>
      <webElementGuid>be8fffab-f5ae-4851-b1e6-3b8085749e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Define Queue Rules'])[1]/preceding::button[2]</value>
      <webElementGuid>1dcc40b3-81e8-48cb-83fb-6ecfad067f04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next: Define Rules']/parent::*</value>
      <webElementGuid>bf8cdb8e-131f-473b-93c4-e7b39a746e93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>606d2ea5-b5e8-4dba-9e06-03de576d81f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'queue-wizard-move-to-members-btn' and (text() = 'Next: Define Rules' or . = 'Next: Define Rules')]</value>
      <webElementGuid>00e56bca-bdd5-42bd-8318-2d01cf11700d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
