<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next Define Members</name>
   <tag></tag>
   <elementGuidId>d9220963-704e-4656-bd63-bd7f0675255a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form[name=&quot;queueRules&quot;] > div.full-width.wz-step-height > div.ingestion-modal-footer > #queue-wizard-move-to-rules-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='queue-wizard-move-to-rules-btn'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f0134481-931d-423d-8251-9199e0ac21f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>9d19fcb7-e064-4665-b575-9ffb095aedf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary pull-right btn-sm margin-top-lg margin-right-lg</value>
      <webElementGuid>cbda5a60-1ecc-43cb-8745-5f4381564ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>queue-wizard-move-to-rules-btn</value>
      <webElementGuid>e71e10c9-b8e2-404c-8f5c-1a7b475f004a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>$ctrl.nextPageLoading</value>
      <webElementGuid>bc8d7e28-d58b-4d32-a1eb-f6f2999190a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next: Define Members</value>
      <webElementGuid>4c36404e-74be-4416-83e1-fbda8c48c484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[@class=&quot;animated fadeIn modal-open&quot;]/div[@class=&quot;modal modal-ingestion ng-scope ng-isolate-scope in&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/queue-wizard[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;modal-body padding-0 queue-wizard&quot;]/div[@class=&quot;cs-wizard ingestion-steps queue-wizard-steps ng-isolate-scope&quot;]/div[@class=&quot;steps ng-scope&quot;]/section[@class=&quot;ingestion-modal-padding wz-reviewoptions-step step ng-scope ng-isolate-scope current&quot;]/form[@class=&quot;ng-scope ng-dirty ng-valid-parse ng-valid ng-valid-required&quot;]/div[@class=&quot;full-width wz-step-height&quot;]/div[@class=&quot;ingestion-modal-footer&quot;]/button[@id=&quot;queue-wizard-move-to-rules-btn&quot;]</value>
      <webElementGuid>184164ca-9cd4-46ba-ac6e-5b5de3daefaa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='queue-wizard-move-to-rules-btn'])[2]</value>
      <webElementGuid>ed7a428f-363b-4ae6-8d48-eb30a2b7adb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::button[1]</value>
      <webElementGuid>923f736b-3ec1-4c3a-b31f-a3359439543f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Very High'])[1]/following::button[2]</value>
      <webElementGuid>327cc97b-49e6-4467-b12c-8f7ca6c8378d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Queue Members and Ownership'])[1]/preceding::button[2]</value>
      <webElementGuid>162fa3c9-5e98-4901-859b-3f269d2fcde8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next: Define Members']/parent::*</value>
      <webElementGuid>de125387-6aa4-4619-a05b-f14b60d16367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/form/div/div[2]/button[2]</value>
      <webElementGuid>a5258b4f-c071-47bc-8c51-58d214331b73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'queue-wizard-move-to-rules-btn' and (text() = 'Next: Define Members' or . = 'Next: Define Members')]</value>
      <webElementGuid>dff46e48-84f0-4901-99ac-05d875b52497</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
