<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Create New Queue</name>
   <tag></tag>
   <elementGuidId>4761f2e8-8d88-4222-9fc4-82905f0fbc70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add-queue-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='add-queue-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>66cf80cc-a85f-472b-9099-955ac977872b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-queue-btn</value>
      <webElementGuid>f71441f3-d32a-4036-9c61-76f3afb4667f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add Queue</value>
      <webElementGuid>dbfb3625-52dd-456b-94d7-5d79d4ee7d23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-hide</name>
      <type>Main</type>
      <value>gridOptions.csOptions.enableSelectMenu &amp;&amp; !gridOptions.csOptions.allowAddRelations &amp;&amp; getSelectedCount() > 0</value>
      <webElementGuid>7a7d14f9-eec3-43a5-80e0-31c6ca18b86f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-action btn btn-sm cs-btn btn-primary margin-left-negative-3 ng-binding ng-scope</value>
      <webElementGuid>8cb9175c-53ae-4d7f-aa0f-f567213a3cf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ea9b5c9a-f389-4f47-a49f-47948c539c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>gridOptions.csOptions.onAdd()</value>
      <webElementGuid>60c80329-d2a3-4fa8-b132-1e9833013011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-if</name>
      <type>Main</type>
      <value>gridOptions.csOptions.allowAdd || gridOptions.csOptions.allowAddRelations</value>
      <webElementGuid>d83e51d9-7af3-4fa1-97ac-b4554fbc6297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9bae6a73-af0c-4b91-8a4a-f6376b7a02aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create New Queue</value>
      <webElementGuid>7871147e-1fcf-435a-b312-566267c44068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-queue-btn&quot;)</value>
      <webElementGuid>7eb7a12e-ffbd-4298-a885-7f926c9f84b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='add-queue-btn']</value>
      <webElementGuid>a6309146-44cb-40b4-8599-dfece91cc914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='queueList']/div/div/div[3]/div/div/button[2]</value>
      <webElementGuid>c90dc4b5-cb00-4fcc-b083-43902333aafd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Queues'])[1]/following::button[3]</value>
      <webElementGuid>0147ccf8-8c12-4a66-8322-976c1f5714af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shift Management'])[1]/following::button[3]</value>
      <webElementGuid>133c040a-abe2-4fa0-8fb0-59b6cb99edb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID'])[1]/preceding::button[5]</value>
      <webElementGuid>7549c417-fe2d-4957-97d1-99abf4a850fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::button[5]</value>
      <webElementGuid>fd2c4e54-fe2d-447c-a3fa-18c88120b3c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create New Queue']/parent::*</value>
      <webElementGuid>efb25412-a4d0-4025-8b65-e75f33709d04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button[2]</value>
      <webElementGuid>d0ffad38-43bd-4a01-b68c-82037930d862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'add-queue-btn' and @title = 'Add Queue' and @type = 'button' and (text() = 'Create New Queue' or . = 'Create New Queue')]</value>
      <webElementGuid>20d36c28-e3a4-493e-a851-8aadd94134ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
