<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next Configure User Assignment</name>
   <tag></tag>
   <elementGuidId>6f98d0b5-49a9-4aa7-92ad-01529a1f1f81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.full-width.wz-step-height.ng-scope > div.ingestion-modal-footer > #queue-wizard-move-to-rules-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='queue-wizard-move-to-rules-btn'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1a1ed158-75ba-4400-88cd-e59b65ef0a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>7ddb66ba-c304-41d1-829b-5d6169b7d961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>$ctrl.saveDraft(false, 'queueOwners')</value>
      <webElementGuid>3a1e9cd5-93f3-48dc-9aed-3c0cc4de092e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary pull-right btn-sm margin-top-lg margin-right-lg</value>
      <webElementGuid>ec40ca2c-eb7f-45bd-9cf3-fea58fb49568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>queue-wizard-move-to-rules-btn</value>
      <webElementGuid>55ec96e8-9e70-4b94-a1e6-6dae452c54b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>$ctrl.nextPageLoading</value>
      <webElementGuid>ddb27390-0af4-4031-9595-d0d876279089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next: Configure User Assignment</value>
      <webElementGuid>44cc0686-2524-443c-989f-3a0a2c900507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[@class=&quot;animated fadeIn modal-open&quot;]/div[@class=&quot;modal modal-ingestion ng-scope ng-isolate-scope in&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/queue-wizard[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;modal-body padding-0 queue-wizard&quot;]/div[@class=&quot;cs-wizard ingestion-steps queue-wizard-steps ng-isolate-scope&quot;]/div[@class=&quot;steps ng-scope&quot;]/section[@class=&quot;ingestion-modal-padding wz-reviewoptions-step step ng-scope ng-isolate-scope current&quot;]/div[@class=&quot;full-width wz-step-height ng-scope&quot;]/div[@class=&quot;ingestion-modal-footer&quot;]/button[@id=&quot;queue-wizard-move-to-rules-btn&quot;]</value>
      <webElementGuid>f0c008c2-da05-4264-87c7-63c650d07035</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='queue-wizard-move-to-rules-btn'])[4]</value>
      <webElementGuid>ef3b6083-0805-4cfa-8877-dfe87295ca35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[2]/following::button[1]</value>
      <webElementGuid>5b8108b0-c8a6-478d-909a-d5bcd031da14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Assignment Preferences'])[1]/preceding::button[2]</value>
      <webElementGuid>316d0e50-7b3d-46c0-95ed-72a8bcd634e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next: Configure User Assignment']/parent::*</value>
      <webElementGuid>5dbbafae-e84e-4833-b53a-774e49245a7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div/div[2]/button[2]</value>
      <webElementGuid>b04b3bec-f9cd-42b9-aa6a-b7eaa24d8435</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'queue-wizard-move-to-rules-btn' and (text() = 'Next: Configure User Assignment' or . = 'Next: Configure User Assignment')]</value>
      <webElementGuid>787e6fa5-c1e3-475f-a093-17afede6418d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
