<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Queue Name_name_1_2</name>
   <tag></tag>
   <elementGuidId>7f3df4ac-2e0b-4a36-8305-7613dca265ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#queueDefinition-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='queueDefinition-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>74b50f17-c861-4efc-8a0a-bcc60937976c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-hide</name>
      <type>Main</type>
      <value>field.value.includes('resolveVault')</value>
      <webElementGuid>ba112f55-3b8f-44a7-aacc-1be0026ca3cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-required</name>
      <type>Main</type>
      <value>field.required</value>
      <webElementGuid>e5f82724-8a92-4dc2-9068-f4db5acb128f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>queueDefinition-name</value>
      <webElementGuid>4f8305dd-34e0-41b7-b6b9-46633a36607f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4131e344-f472-4a96-843f-02a2e58b77a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>f03c3b9a-f265-4ca1-85e3-2f0641ec9b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>2b61e925-34ab-4ba3-bcc0-faa34989199a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control  ng-isolate-scope ng-touched ng-not-empty ng-dirty ng-valid ng-valid-required grid-active-filter ng-valid-parse</value>
      <webElementGuid>20ec63d8-5995-4e6d-8f16-54b4b8038e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7cd24704-5518-40ee-bde5-70a71e9bb7cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-readonly</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>9e51b0e1-50e7-48fb-9ef5-7f46064a4d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Create a name for the queue</value>
      <webElementGuid>525d5c4a-28f4-4456-b8d0-2d9d6fe03657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-change</name>
      <type>Main</type>
      <value>changeMethod(value, field)</value>
      <webElementGuid>2e198923-2d4e-4a7c-8b69-fd644c9bad71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-blur</name>
      <type>Main</type>
      <value>blurMethod(value)</value>
      <webElementGuid>bd409ab2-d661-4c45-b0f3-dcaa7b000a11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-focus</name>
      <type>Main</type>
      <value>focusMethod($event)</value>
      <webElementGuid>500d1d82-f922-4abf-b014-11af19ca016e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>::{'input-big': size === 'large', 'input-sm': size === 'small'}</value>
      <webElementGuid>29ea21d8-dac6-45ed-8deb-779c8c255e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-maxlength</name>
      <type>Main</type>
      <value>1024</value>
      <webElementGuid>9e2e29c8-d486-476b-9da9-85d4df897aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-minlength</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>887019f8-b200-4c1f-9900-d99fa1d3390f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enable-jinja</name>
      <type>Main</type>
      <value>enableJinja</value>
      <webElementGuid>831a8b53-4eba-4923-ba49-1f6de57ad517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enable-record-fields</name>
      <type>Main</type>
      <value>enableRecordFields</value>
      <webElementGuid>b5187755-c921-4c94-bfaa-fdb8b4b246de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Aut</value>
      <webElementGuid>b3829db0-00dc-4bcf-93a9-3be03d448726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a74d3b35-e319-496c-98bc-6f27ddf837f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>5c212a48-5c50-4cd3-ad0b-daecd4e20e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bdac09c4-6535-4c73-8ca6-6a5a2908b386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;queueDefinition-name&quot;)</value>
      <webElementGuid>56470b42-0b02-48d9-b290-3949b6746c88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='queueDefinition-name']</value>
      <webElementGuid>71eb004d-82c9-4127-aca0-f13234222af1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>f1729fbd-a785-4bab-b7e4-d90858a28355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'queueDefinition-name' and @type = 'text' and @name = 'name' and @placeholder = 'Create a name for the queue' and @title = 'Aut']</value>
      <webElementGuid>911ecc31-75b3-42c5-bf9d-0d10110c6f8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
