<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select a field_search-input</name>
   <tag></tag>
   <elementGuidId>7630a5b6-de5b-4eec-b1d9-b2fc17eaff12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;search-input&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='search-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4b4d47c-c36f-46ac-bab8-be9fed5ecae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5f50950f-21ad-4d03-928e-9ac735050bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control filter-height-style ng-untouched ng-valid ng-not-empty ng-dirty ng-valid-parse</value>
      <webElementGuid>f702ba5c-0669-4169-9292-314a2ca3353c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>searchField($event)</value>
      <webElementGuid>f185e331-c9f2-4881-ab61-e13620de10fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>params.srchBox</value>
      <webElementGuid>1664ec73-c18b-4223-af53-c221e0bebe03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>4006b902-a985-4df0-96b8-f600666066ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>search-btn</value>
      <webElementGuid>b833952a-28e6-4a37-87d2-5f5c89491ece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search-input</value>
      <webElementGuid>ad20f507-067f-479b-ab32-5b7259efda8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4cd3da0d-ea81-4a20-adbc-939d8f5a2f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[@class=&quot;animated fadeIn modal-open&quot;]/div[@class=&quot;modal modal-ingestion ng-scope ng-isolate-scope in&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/queue-wizard[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;modal-body padding-0 queue-wizard&quot;]/div[@class=&quot;cs-wizard ingestion-steps queue-wizard-steps ng-isolate-scope&quot;]/div[@class=&quot;steps ng-scope&quot;]/section[@class=&quot;ingestion-modal-padding wz-reviewoptions-step step ng-scope ng-isolate-scope current&quot;]/form[@class=&quot;ng-scope ng-dirty ng-valid-parse ng-invalid ng-invalid-required&quot;]/div[@class=&quot;full-width wz-step-height&quot;]/div[@class=&quot;row wizard-full-height margin-0&quot;]/div[@class=&quot;col-md-8 padding-bottom-65 padding-top-40 padding-left-45 padding-right-53 wizard-full-height overflow-auto&quot;]/div[@class=&quot;padding-top-md ng-scope&quot;]/div[@class=&quot;dashed-border-section ng-scope&quot;]/div[@class=&quot;padding-lg top-border&quot;]/div[@class=&quot;form-group margin-bottom-lg ng-scope&quot;]/div[@class=&quot;ng-pristine ng-untouched ng-valid ng-isolate-scope ng-not-empty&quot;]/div[@class=&quot;condition-group ng-scope&quot;]/div[@class=&quot;margin-left-sm and&quot;]/div[@class=&quot;condition-div ng-scope&quot;]/div[@class=&quot;row margin-bottom-sm conditions-row ng-scope&quot;]/div[@class=&quot;col-md-4 padding-right-0&quot;]/div[@class=&quot;form-group margin-bottom-0&quot;]/div[@class=&quot;btn-group cd-dropdown dropdown open&quot;]/ul[@class=&quot;dropdown-menu&quot;]/li[@class=&quot;primary-div&quot;]/div[@class=&quot;input-group search-style margin-0 padding-0 margin-left-sm&quot;]/input[@class=&quot;form-control filter-height-style ng-untouched ng-valid ng-not-empty ng-dirty ng-valid-parse&quot;]</value>
      <webElementGuid>3fa76827-afff-4107-bb95-338d33872ec9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='search-input']</value>
      <webElementGuid>00d9e717-2fe5-4bf7-b6e9-840cc976ad64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/input</value>
      <webElementGuid>03fa188a-381d-45ab-afae-28b85aee3221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search' and @name = 'search-input']</value>
      <webElementGuid>c700c81e-9d33-4b7c-99ec-8634640e05e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
