<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enable Shift-Based Assignment_require-shift</name>
   <tag></tag>
   <elementGuidId>d17d3858-32ce-4eea-ba3f-ca88c7f094f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#require-shift</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='require-shift']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27f31ccc-7387-4954-b5bf-1952a4644cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>334598fc-ec74-4a44-a857-1c2144bdefbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>require-shift</value>
      <webElementGuid>4aa5c83a-7892-42ff-a9a5-bd40b99e7780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>require-shift</value>
      <webElementGuid>20f02ff3-b493-49a1-be81-11765524bf9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>$ctrl.entity.fields.assignmentParameters.value.requireShift</value>
      <webElementGuid>6f740004-6214-4d8f-a73e-6b1713eb2558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>dba58e50-2b9a-4c3c-ba0b-86bc5bafb6ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3b175762-93fc-4b43-959a-28d9d7d36d88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;require-shift&quot;)</value>
      <webElementGuid>e7a8a275-82e0-414d-bf3a-0f82497abba6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='require-shift']</value>
      <webElementGuid>b2cae4de-4947-4485-9070-20097fb75295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label/input</value>
      <webElementGuid>1287ebde-7f76-4421-8f90-e887eef7c665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'require-shift' and @name = 'require-shift']</value>
      <webElementGuid>571af723-0efe-4563-ae5a-109baa401f99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
