<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rule Name_rule-name-0</name>
   <tag></tag>
   <elementGuidId>30b58494-7088-480d-ae9f-75ad5c3913d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rule-name-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rule-name-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>101e7d81-e13c-4770-a851-c88cc95c8133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6286d77d-2378-468e-aabb-c55825bc83f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required</value>
      <webElementGuid>9bee80eb-00bf-4331-b20c-fd3f722ba74a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>rule.name</value>
      <webElementGuid>7115750a-5100-4c17-b02d-edd3aec37773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rule-name-0</value>
      <webElementGuid>d634935e-50a1-44c7-bf3a-9ad93f3d0b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rule-name-0</value>
      <webElementGuid>9447ea1b-9cd4-48eb-bf3d-3253081015b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b8732ec1-00f5-4541-9f42-d3f7b87886ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rule-name-0&quot;)</value>
      <webElementGuid>938107d0-f002-4333-a559-f83982083e71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rule-name-0']</value>
      <webElementGuid>05dff8bb-23fb-4342-99ea-af46ee31e5d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>ae1c4a37-e561-494d-bd7a-fb6502b3a0dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'rule-name-0' and @id = 'rule-name-0']</value>
      <webElementGuid>880678f8-684a-4765-a50b-3388bc090912</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
