<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Duration (Hours)_duration_hours</name>
   <tag></tag>
   <elementGuidId>314df43b-1937-45a0-8df2-edeba7d1cc3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#duration_hours</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='duration_hours']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ed6047bf-2b7f-4078-a809-6a534c53e355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>6695cbbb-540b-4b52-bc03-d7ac6387140c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-valid-min ng-dirty ng-touched ng-empty ng-valid-parse ng-invalid ng-invalid-required</value>
      <webElementGuid>b0a97197-aadb-4a1a-ac98-02f84c409fa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>duration_hours</value>
      <webElementGuid>153af49e-d7e7-4929-bd2d-900edadf2787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>duration_hours</value>
      <webElementGuid>b09268c3-5fc4-43a9-a2fe-62c97d976758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9a24a5b2-9af7-4e91-81b1-f68458dbb9ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>$ctrl.settings.duration.hours</value>
      <webElementGuid>96898477-e81c-46aa-a972-75d231f51a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Hours</value>
      <webElementGuid>ffc6059e-33e3-48bc-bf79-ff677d898d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ebb696d8-419e-4ab8-91bb-576789db7810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;duration_hours&quot;)</value>
      <webElementGuid>4c838d79-3956-4db9-8137-4862aa9092ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='duration_hours']</value>
      <webElementGuid>73f8553e-a53e-4f01-9790-7bffb8d8aff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>7c1902b9-7f59-452d-a8b1-bbda06d3c20e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'duration_hours' and @name = 'duration_hours' and @placeholder = 'Hours']</value>
      <webElementGuid>1a6e12b3-5554-44e7-b1c3-508fafa0f49d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
