<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Generate</name>
   <tag></tag>
   <elementGuidId>6b322500-1cd5-4b7e-9243-6b63be507b37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#generate-shifts-btn > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='generate-shifts-btn']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d33fc865-52be-4cf0-8800-4c351232d123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-hide</name>
      <type>Main</type>
      <value>$ctrl.saveProcessing</value>
      <webElementGuid>c9804b2e-2378-479d-8fc8-ba27a42f4efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f7e0b3de-87d8-43c1-b290-a57eb2ade16b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Generate</value>
      <webElementGuid>d5be1a6e-da4b-44de-bd87-2aafa2d48cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;generate-shifts-btn&quot;)/span[1]</value>
      <webElementGuid>daa4e407-8517-4920-9422-1aa6c885ac57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='generate-shifts-btn']/span</value>
      <webElementGuid>7900bfc3-4fd3-45bd-85dd-cf0a7964500c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='{}'])[1]/following::span[1]</value>
      <webElementGuid>17f0b5ab-fec6-47e3-a34f-e950200a2fcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CS Admin (me)'])[1]/following::span[3]</value>
      <webElementGuid>b10f2ca4-3941-4ef9-a0d0-f8968a8916e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::span[4]</value>
      <webElementGuid>e6c2dd3d-b1be-4fc8-8dfb-d3737b638f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle Navigation'])[1]/preceding::span[5]</value>
      <webElementGuid>5cad9f99-ee1e-410a-90df-4776c3299310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button/span</value>
      <webElementGuid>16b7bb27-b116-46e4-9802-135f7d75a0dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Generate' or . = ' Generate')]</value>
      <webElementGuid>b3df1f12-3527-4fed-a1ed-c5418f82164a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
