<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_CS Admin</name>
   <tag></tag>
   <elementGuidId>c9a0aa4d-380f-49ba-9294-c7ce9bbe7119</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ng-binding.ng-scope</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/assignment-automation/div/div/div[2]/shift-calendar/div/div[3]/div[2]/div/div[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c8cc6bff-16a0-41a7-9e96-8cc224dc400f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>shift.leader</value>
      <webElementGuid>f6bda732-2cf2-4f89-b486-947f69f40caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding ng-scope</value>
      <webElementGuid>22b80586-9750-4f45-9f74-a6a511df9cf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CS Admin</value>
      <webElementGuid>0e28dd8a-9f32-4f2c-a5c0-cb5f73fded9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/assignment-automation[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;porting-history ng-isolate-scope&quot;]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;tab-pane ng-scope active&quot;]/shift-calendar[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;shift-weeks&quot;]/div[@class=&quot;shift-day ng-scope&quot;]/div[@class=&quot;shift-item ng-scope border-left-active&quot;]/div[@class=&quot;row margin-0&quot;]/div[@class=&quot;col-md-2 cell&quot;]/span[@class=&quot;ng-binding ng-scope&quot;]</value>
      <webElementGuid>d2ec6c20-c24c-48fa-b484-63e2c33021bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/assignment-automation/div/div/div[2]/shift-calendar/div/div[3]/div[2]/div/div[3]/span</value>
      <webElementGuid>95028cd1-bb00-49f1-ae26-8aa004fbffc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Current Shift'])[1]/following::span[2]</value>
      <webElementGuid>e1010424-f43f-4412-9b2f-b5a997a796b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wednesday, August 24 2022'])[1]/preceding::span[1]</value>
      <webElementGuid>c1fc8f02-d9f5-468e-b442-4331101066e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Current Shift'])[2]/preceding::span[1]</value>
      <webElementGuid>300225a5-230f-4508-84cb-44a599518e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span</value>
      <webElementGuid>121556bc-5040-4613-b337-99d505df8f96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'CS Admin' or . = 'CS Admin')]</value>
      <webElementGuid>09a47425-db9c-43ec-ab65-fae3f62f85a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
