<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Alert From Automation 01</name>
   <tag></tag>
   <elementGuidId>d17c7ced-4c67-4be9-8d82-d907794afbc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#view-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='view-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>18dc4840-bd09-42a4-9374-fe2edc482d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>view-name</value>
      <webElementGuid>1bf8dc0c-cfb9-48f3-acb0-5e61bf049804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>field.type !== 'url'</value>
      <webElementGuid>dda67393-cd4e-4edc-a2c4-675293c66c6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>word-break read-only-item margin-0 ng-binding ng-scope</value>
      <webElementGuid>0c48e92b-e048-4ec6-9a18-1bb021dac68f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Alert From Automation 01</value>
      <webElementGuid>a0b2f043-58ff-41e2-a7c3-530579aa5143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-bind</name>
      <type>Main</type>
      <value>displayResult</value>
      <webElementGuid>b8f8611b-e432-4c94-aa24-046139438ba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{'filehash-field': field.type==='filehash'}</value>
      <webElementGuid>a0068149-1c9c-4c40-bc07-36702cd23d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alert From Automation 01</value>
      <webElementGuid>168b0023-eec4-40e8-96e2-05387334d1c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;view-name&quot;)</value>
      <webElementGuid>746e1104-6090-448b-b8c0-45f7a2ab0310</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='view-name']</value>
      <webElementGuid>3e9b4c61-fbd8-4ff8-89b5-e165dff43ce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::p[1]</value>
      <webElementGuid>890281fc-ec93-49d4-8eca-6b01521eb909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/following::p[1]</value>
      <webElementGuid>454da9d7-4d3f-4d09-8c56-8fbb2846aff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Modified 08/22/2022 02:00 PM by Playbook'])[1]/preceding::p[3]</value>
      <webElementGuid>d9e2f33d-7029-4139-a873-5e77e1382221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tags'])[1]/preceding::p[3]</value>
      <webElementGuid>4cab80d0-caf4-4ce1-b6c0-411087c920fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Alert From Automation 01']/parent::*</value>
      <webElementGuid>aabeee84-2e0a-4511-8444-ef1bd216f277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ng-form/div/div/div/div/p</value>
      <webElementGuid>0201728e-b822-4f7e-a875-0a725da5dc8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'view-name' and @title = 'Alert From Automation 01' and (text() = 'Alert From Automation 01' or . = 'Alert From Automation 01')]</value>
      <webElementGuid>7facd7f6-d5c8-4e3f-b564-d0a9177d1481</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
