<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>39dbb5af-dcb6-47f7-bb49-8efb76634666</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#breadcrumb-add</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='breadcrumb-add']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2d6b333e-ccea-4828-98a9-f3c34cec3ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>breadcrumb-add</value>
      <webElementGuid>76cba2df-bdf3-4442-a26a-2c345c562141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ec1ba0fb-f28e-4a14-bf23-b0fd03c466ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>save()</value>
      <webElementGuid>7d492cf1-9d6c-4faa-9656-338464570f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-primary margin-right-negative-2</value>
      <webElementGuid>2be3b82e-af01-4df5-9479-4f5e6a6c28e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-disabled</name>
      <type>Main</type>
      <value>processing</value>
      <webElementGuid>34baafc0-f3d1-4e09-8326-f6203a8f1884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-show</name>
      <type>Main</type>
      <value>mode === 'add' &amp;&amp; permission.create || mode === 'edit' &amp;&amp; permission.update</value>
      <webElementGuid>57b6aa95-5560-4d97-8ede-dd2ab65b65bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>01bad0b7-37b8-4b84-8fa4-85f4b6d6c5a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Save</value>
      <webElementGuid>a8745268-9b57-44a3-8d14-f5e0de97bb61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;breadcrumb-add&quot;)</value>
      <webElementGuid>4239bb6b-79d0-493e-8029-d75e5f2816f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='breadcrumb-add']</value>
      <webElementGuid>7818d6ed-310d-4c25-b1a4-31dcd38aa8c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-view-template']/div/div/form/div/div[2]/div/div/div/button</value>
      <webElementGuid>fc0cb1bb-9c53-4d9b-95f6-ba3fbccbc2b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ Add Tags'])[1]/following::button[1]</value>
      <webElementGuid>75a8fc72-304a-4424-ae2f-3b4b475fc5e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[16]/preceding::button[1]</value>
      <webElementGuid>91c5e0d9-44e4-46a2-ae03-8ff6a27c94c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>447e5ce5-ea87-4d03-86f7-66482b4d776d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button</value>
      <webElementGuid>32387a38-4394-4f1e-a0c6-c4a9ec840290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'breadcrumb-add' and @type = 'button' and (text() = ' Save' or . = ' Save')]</value>
      <webElementGuid>9dee5ec8-47c0-4fce-a8d1-9b884f16ca9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
