<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Alert-2</name>
   <tag></tag>
   <elementGuidId>3a793c55-111e-40a0-8adb-caea8c1e41c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3.margin-0.pull-left.margin-top-6.ng-binding.ng-scope.margin-left-md</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>0dace140-f1ef-4c9d-9f81-e9f52006c971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>margin-0 pull-left margin-top-6 ng-binding ng-scope margin-left-md</value>
      <webElementGuid>ac6bd1ce-e254-4ceb-af7d-15e6c8e92515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{'margin-left-md': picklistField &amp;&amp; picklistField.type === 'picklist'}</value>
      <webElementGuid>f77b0081-6acb-4232-a3d3-bfe39f17da4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-if</name>
      <type>Main</type>
      <value>idField</value>
      <webElementGuid>712f89d3-5b41-420c-998a-93dff709b585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alert-2</value>
      <webElementGuid>059ab79f-0f32-425a-8ed3-b96be735fbc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[@class=&quot;animated fadeIn modal-open&quot;]/div[@class=&quot;modal modal-panel no-animation fade ng-scope ng-isolate-scope in&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/data-ui-view[@class=&quot;ng-scope&quot;]/ui-view[@class=&quot;ng-scope&quot;]/div[@class=&quot;view-panel ng-scope&quot;]/div[@class=&quot;padding-right-0 overflow-auto full-width view-panel-container&quot;]/div[@class=&quot;modal-header padding-right-0&quot;]/div[@class=&quot;cache-breadcrumb position-relative&quot;]/div[@class=&quot;pull-left&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;padding-left-lg padding-top-xlg padding-bottom-sm margin-left-negative-2 ng-scope&quot;]/div[@class=&quot;row ng-scope&quot;]/div[@class=&quot;primary-box col-md-12&quot;]/div[@class=&quot;display-flex&quot;]/h3[@class=&quot;margin-0 pull-left margin-top-6 ng-binding ng-scope margin-left-md&quot;]</value>
      <webElementGuid>fb53378a-6239-4878-b25b-4cbf8aed83f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='High'])[3]/following::h3[1]</value>
      <webElementGuid>91779a00-2e09-47ed-8f55-26d2e9b7d00a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='High'])[2]/following::h3[1]</value>
      <webElementGuid>d48c9b15-c29a-4f12-b066-10608de3bd35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::h3[1]</value>
      <webElementGuid>ffc825e6-59e8-4b72-8996-6accaf02719e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::h3[1]</value>
      <webElementGuid>5d749e8a-e467-470f-9cde-c35e138c2aca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Alert-2']/parent::*</value>
      <webElementGuid>e729e9f5-4e88-428a-a9d4-5b8fb28499de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>acf0189c-4542-4ca7-8bf2-ad8199eb3df6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Alert-2' or . = 'Alert-2')]</value>
      <webElementGuid>f8af1e2a-4b83-44df-98af-d18cba701578</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
