<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>9bbdaaf2-f79b-4705-b91c-aec932f0a3ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ui-grid-selection-row-header-buttons.ui-grid-icon-ok.clickable.ng-pristine.ng-untouched.ng-valid.ng-scope.ng-not-empty.ui-grid-row-selected</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='1661198916616-0-uiGrid-0057-cell']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f206ed87-a091-4fac-a6c5-2d996b552017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-grid-selection-row-header-buttons ui-grid-icon-ok clickable ng-pristine ng-untouched ng-valid ng-scope ng-not-empty ui-grid-row-selected</value>
      <webElementGuid>c8900e38-77d4-45f1-80ea-2e3d26a7772a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'ui-grid-row-selected': row.isSelected}</value>
      <webElementGuid>a9f21713-7d8e-4f14-90b1-cd115912672e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>216dfe31-dcd3-45b2-95e8-efa5fab08f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>selectButtonClick(row, $event)</value>
      <webElementGuid>63830828-ac79-42a5-a472-a7efea724f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-keydown</name>
      <type>Main</type>
      <value>selectButtonKeyDown(row, $event)</value>
      <webElementGuid>55198147-2519-4252-8ebd-5dd74754bfc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-aria-label</name>
      <type>Main</type>
      <value>{{('selection.aria.row' | t) + ' ' + (row.index + 1) + ', ' + col.displayName}}</value>
      <webElementGuid>770db0f1-33b6-451b-ac28-6ba50a9c4a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c209bed8-8a6c-44d0-8281-22b7570b6111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>895c380a-8f3f-41db-b1bb-58878817b7a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>row.isSelected</value>
      <webElementGuid>48d4fc92-bd9e-49f5-82e7-c51e58180afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Row 1, Row Selection Checkbox</value>
      <webElementGuid>5a1b178f-5515-43a0-bd56-083c3f7af61e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>320dd25e-3be1-48d2-962b-05c81cc04d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>b24bb8c5-930c-4d17-b3c7-0aac554dcfc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1661198916616-0-uiGrid-0057-cell&quot;)/div[@class=&quot;ui-grid-cell-contents ui-grid-disable-selection clickable ng-scope&quot;]/div[@class=&quot;ui-grid-selection-row-header-buttons ui-grid-icon-ok clickable ng-pristine ng-untouched ng-valid ng-scope ng-not-empty ui-grid-row-selected&quot;]</value>
      <webElementGuid>45a8684c-dce4-4b49-8bec-4baa69866659</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1661198916616-0-uiGrid-0057-cell']/div/div</value>
      <webElementGuid>408aa07f-f6f7-485f-8d58-ab936cb09865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Saved Filters Available'])[1]/following::div[27]</value>
      <webElementGuid>d5305347-1254-4cc1-994f-c3094bb51e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contains'])[1]/following::div[29]</value>
      <webElementGuid>f6f675ed-5d75-4a97-95fc-bcbf77c59a58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[1]/preceding::div[2]</value>
      <webElementGuid>2ab9cea1-5170-40ce-bbc3-671fbcff7fe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[1]/preceding::div[29]</value>
      <webElementGuid>381df91f-4ed2-47f8-9dd6-cea8ae877c46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div[2]/div/div[2]/div/div/div/div/div/div/div</value>
      <webElementGuid>798f86f1-338a-454b-9c97-f563f7aaa3f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' ' or . = ' ')]</value>
      <webElementGuid>e6e222db-c37c-4d06-98c9-2cf92d3fc746</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
