<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Showing1 Items</name>
   <tag></tag>
   <elementGuidId>b36231ee-cd56-4414-b6f1-4c03134addcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.tau.grid-selected-txt.muted.ng-binding.margin-left-lg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='usersGrid']/div/div/div[3]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5ecb3346-8e53-4a46-8142-364f376dd767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tau grid-selected-txt muted ng-binding margin-left-lg</value>
      <webElementGuid>911689b9-bf0e-4a86-a2b1-4925e319f8c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{'pull-left': gridOptions.lightMode, 'margin-left-2': gridOptions.expandableRowHeaderTitle, 'margin-left-lg': !gridOptions.expandableRowHeaderTitle, 'light-mode-grid-container': gridOptions.lightMode}</value>
      <webElementGuid>914f7707-82dd-47d6-8e9d-83786cf88d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-hide</name>
      <type>Main</type>
      <value>gridOptions.csOptions.enableSelectMenu &amp;&amp; getSelectedCount() > 0</value>
      <webElementGuid>b112be73-42be-4f4b-ad3b-779f50bb2f85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e193c146-eeb3-41a6-806f-3368f6b0e487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Showing 1 Items</value>
      <webElementGuid>b6d4f4f9-9358-4fd0-8f20-483a651d056c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;usersGrid&quot;)/div[@class=&quot;grid-actions fade-in-animation padding-right-53&quot;]/div[@class=&quot;row ng-scope&quot;]/div[@class=&quot;col-md-12 padding-left-0 padding-top-sm col-lg-9&quot;]/div[@class=&quot;padding-top-sm margin-right-2 margin-top-3 padding-left-3 margin-left-md&quot;]/span[@class=&quot;tau grid-selected-txt muted ng-binding margin-left-lg&quot;]</value>
      <webElementGuid>196adfbc-8030-4af7-a97b-acdf572cf3db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='usersGrid']/div/div/div[3]/div/span</value>
      <webElementGuid>870ad3b1-9701-4555-b419-d2da3235ef50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Users'])[1]/following::span[2]</value>
      <webElementGuid>49839a65-6d66-473a-adfa-0563b060aec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set As Super Admin'])[1]/following::span[2]</value>
      <webElementGuid>f7f34e17-ac12-4547-b403-deda7975f839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[1]/preceding::span[3]</value>
      <webElementGuid>ce9902e9-ea8b-452f-86c0-cb11988d4b8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CLEAR FILTER CRITERIA'])[1]/preceding::span[11]</value>
      <webElementGuid>5383ffe3-0316-4897-89d6-af7915432509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1 Items']/parent::*</value>
      <webElementGuid>5c034383-0b4b-49b1-acf0-b60ea0aae87f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[3]/div/span</value>
      <webElementGuid>a04a0a59-9878-4ddc-846c-1d3571229a8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Showing 1 Items' or . = 'Showing 1 Items')]</value>
      <webElementGuid>871842cb-4dcf-424c-906a-ebf38ee6a729</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
