<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Modules</name>
   <tag></tag>
   <elementGuidId>4e2cde6a-a5cb-4019-a51c-0a51cac4708b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#navigation-link-modules</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='navigation-link-modules']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ec211733-30dc-4991-a4cb-2c7a42aa5628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-if</name>
      <type>Main</type>
      <value>!(isDemo &amp;&amp; page.demoEnabled === false)</value>
      <webElementGuid>e24d8c9e-5a80-4630-b1eb-c36ec0605350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui-sref</name>
      <type>Main</type>
      <value>main.editor.modules({tenant: &quot;Master&quot;})</value>
      <webElementGuid>c8027d28-4ea9-4693-87d3-7e61f3b16afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-bind</name>
      <type>Main</type>
      <value>::page.heading</value>
      <webElementGuid>c5b11c4c-4d75-4f01-8e9b-de454b07d9b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>navigation-link-modules</value>
      <webElementGuid>ff42298d-3ae3-4161-a0f0-62970d82d1c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding ng-scope</value>
      <webElementGuid>11b7b44b-a096-4b75-a617-488925a3b1a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/editor/Master/modules/</value>
      <webElementGuid>bd3ec8b4-ebd8-4559-9d99-bad399b1d695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Modules</value>
      <webElementGuid>872e2421-caab-46f1-bca6-b649b1a31132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navigation-link-modules&quot;)</value>
      <webElementGuid>c9c108cb-f5aa-4aca-b4e8-218cc60cfb44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='navigation-link-modules']</value>
      <webElementGuid>26efe534-d56d-48a6-a631-56ae77a44d41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='admin']/div/div[4]/ul/li/a</value>
      <webElementGuid>ce76c210-4c6f-4fd4-900a-36bb20463494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Modules')]</value>
      <webElementGuid>658c3dde-e0c7-4018-9702-902d05a2ce59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application Editor'])[1]/following::a[1]</value>
      <webElementGuid>c0055800-7615-4420-abfc-b4ba60e6c5de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password Vault'])[1]/following::a[1]</value>
      <webElementGuid>b8bbfafd-7526-4949-a476-4e1188b465aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Picklists'])[1]/preceding::a[1]</value>
      <webElementGuid>8e66cb8a-1501-45c7-8ec6-151dde8baa1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Navigation'])[1]/preceding::a[2]</value>
      <webElementGuid>4466f55c-eb14-40f3-80db-09a4f34159a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Modules']/parent::*</value>
      <webElementGuid>7a15103b-0da4-4a15-9b40-e4d2c5cbd65f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/editor/Master/modules/')]</value>
      <webElementGuid>e6178dbb-8a4b-40b1-a954-a220ddb5c3de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li/a</value>
      <webElementGuid>f9f62932-2042-459a-831f-59b530f1b6df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'navigation-link-modules' and @href = '/editor/Master/modules/' and (text() = 'Modules' or . = 'Modules')]</value>
      <webElementGuid>0cee05f2-2073-4dc3-b412-d23024ce4e90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
