<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>12533c31-6fc1-4770-9b74-ae90c2bbb728</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#save-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='save-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5f6baac8-bb17-4dda-a9c5-600c078e8b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>save-btn</value>
      <webElementGuid>835c54d8-15c8-4566-884a-8e1deeb1d72c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>260a1357-a0c2-42db-8e0b-e8a609bb9006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-primary margin-right-negative-2 padding-right-lg</value>
      <webElementGuid>d8c6668a-fbfc-4bff-bca7-a439907597d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-hide</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>3b42a4f7-ac68-4733-92f9-1eeb6dc70f33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-disabled</name>
      <type>Main</type>
      <value>(!actorForm.$dirty &amp;&amp; mode === 'Edit') || (isLdapUser &amp;&amp; (user.credentials.bind_name.value === null || user.credentials.bind_name.value.length === 0))</value>
      <webElementGuid>bdd058c4-c940-484a-b91e-c9d3f98b90f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e9b6fc76-c12f-4282-befe-59ff2a380cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>94f61046-c119-4ad1-ac0c-5da1dd12b934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;save-btn&quot;)</value>
      <webElementGuid>2cb5aed8-4ae1-479f-ba46-9fa37190002c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='save-btn']</value>
      <webElementGuid>c94c259e-1811-495e-a2fb-74822aafd3a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='admin-pane']/div/div/div/form/div[2]/button</value>
      <webElementGuid>2d017a03-790a-4a4d-9bb2-272b7297a492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New User'])[2]/following::button[1]</value>
      <webElementGuid>3749611b-a6de-4852-8a23-57de4a7f01d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Import Wizard'])[1]/following::button[1]</value>
      <webElementGuid>b3d8a1fa-3d51-49d4-9e85-2e9fba26001b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[16]/preceding::button[1]</value>
      <webElementGuid>f0da82e1-9e01-45fd-ab60-24424446e70b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select User Category'])[1]/preceding::button[2]</value>
      <webElementGuid>4be8f594-e8ac-4b02-a506-c734c0337bb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>821e8928-94ba-413f-96ba-529ffdb246ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/button</value>
      <webElementGuid>b31c1cae-3b7e-4386-99cf-c0aac1594bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'save-btn' and @type = 'submit' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>8b040d1c-45c4-4d35-b73d-47b11fd808a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
