<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__lastname</name>
   <tag></tag>
   <elementGuidId>9c168037-2e55-4382-87c4-509d39de6f43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#actorForm-lastname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c6984db-5a9c-41d7-a4be-13d53f1075d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-hide</name>
      <type>Main</type>
      <value>field.value.includes('resolveVault')</value>
      <webElementGuid>bb8f02d2-25a7-4120-bb18-6540372268c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-required</name>
      <type>Main</type>
      <value>field.required</value>
      <webElementGuid>0bacedc8-83f2-4400-94fa-a7abe77c412c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actorForm-lastname</value>
      <webElementGuid>b42db684-4363-416d-a862-ef7981d5cc9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>016e659f-8f7c-4601-ae38-27fab54d19f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lastname</value>
      <webElementGuid>792c422b-ae06-41ed-8c9d-58ced9a40c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>2ba603f6-89ff-41dd-a97c-800cb3a370e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control  ng-isolate-scope</value>
      <webElementGuid>933ac264-1c92-4b69-b4d7-47296adae6cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2bb6469b-1533-4c73-a41c-2b4ecabf87c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-readonly</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>3af8feba-97aa-4557-9a69-b33cb44b6542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-change</name>
      <type>Main</type>
      <value>changeMethod(value, field)</value>
      <webElementGuid>be8ef13d-24b4-4327-86a4-ecdce53e01e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-blur</name>
      <type>Main</type>
      <value>blurMethod(value)</value>
      <webElementGuid>daca6d84-5204-48e6-b4f3-9d2e2bc3ac01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-focus</name>
      <type>Main</type>
      <value>focusMethod($event)</value>
      <webElementGuid>7230731c-8f68-4b34-81d8-39af840cb3eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>::{'input-big': size === 'large', 'input-sm': size === 'small'}</value>
      <webElementGuid>f4f19325-f6e1-4edf-9b05-36ca993fe997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-maxlength</name>
      <type>Main</type>
      <value>1024</value>
      <webElementGuid>8ce4573c-51d3-43fd-8847-df0a8cf4c765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-minlength</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cbc231af-c2ef-4095-9b80-ec44a96ceff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enable-jinja</name>
      <type>Main</type>
      <value>enableJinja</value>
      <webElementGuid>d15fce75-4434-40be-a987-5a4f99c3f2c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enable-record-fields</name>
      <type>Main</type>
      <value>enableRecordFields</value>
      <webElementGuid>50cbd4d8-fe9e-4f40-8aa4-c97c0d99ada8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>25975fd1-57ef-44a6-90f6-12e5169393a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>cb4537e5-9580-417f-802f-1becfbb7e22d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d823ae97-618a-4860-96af-f3787e3505fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actorForm-lastname&quot;)</value>
      <webElementGuid>4e9c2c85-d828-4134-84cd-1b57b80f20d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='actorForm-lastname']</value>
      <webElementGuid>fce69e62-4f2d-43b9-a004-f561ee3a7f79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='admin-pane']/div/div/div/form/div[3]/div/div[3]/div/div[3]/div/div/div[2]/div/div/input</value>
      <webElementGuid>4dcf0399-8660-45ba-bfb5-fd0114c6008f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>1ff18d1b-ab4a-4a53-8678-f2cd64fcaa53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'actorForm-lastname' and @type = 'text' and @name = 'lastname']</value>
      <webElementGuid>c478bc52-733b-4dad-a2c4-4b03e09b3122</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
