<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__lastname_1_2_3</name>
   <tag></tag>
   <elementGuidId>2a8a9219-5393-427b-89ac-39b3c3ae1e14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#actorForm-lastname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='actorForm-lastname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d35d15ec-4566-4a53-8037-d7ec0ed052b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-hide</name>
      <type>Main</type>
      <value>field.value.includes('resolveVault')</value>
      <webElementGuid>fcc7d4ab-ebfe-45b9-b14e-7c4cb92ef340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-required</name>
      <type>Main</type>
      <value>field.required</value>
      <webElementGuid>d8255183-2af6-4b8a-bb9f-63c5541842d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actorForm-lastname</value>
      <webElementGuid>1d889313-9e61-467c-a26f-39da24f76cb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dfe87c9d-7e5d-442d-a08e-1efc7f8ad27c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lastname</value>
      <webElementGuid>4e0b5e15-6d90-4109-86dd-60e7fb7f1c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>6d4c6a92-5c56-4402-a4c5-39306d9aef67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control  ng-isolate-scope ng-not-empty ng-dirty ng-valid ng-valid-required grid-active-filter ng-valid-parse</value>
      <webElementGuid>78c99904-5163-4b34-a4a8-58f823ee404a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>86ccdc51-6a14-4198-963d-9b19ebe29791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-readonly</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>1406f55c-a9a2-4ed4-9c78-4aed350c057a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-change</name>
      <type>Main</type>
      <value>changeMethod(value, field)</value>
      <webElementGuid>7ab2a6d0-ae3c-42a5-90e5-b9e45bc0a449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-blur</name>
      <type>Main</type>
      <value>blurMethod(value)</value>
      <webElementGuid>b84b7e39-1440-4c5b-a07f-c49f6c7c040b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-focus</name>
      <type>Main</type>
      <value>focusMethod($event)</value>
      <webElementGuid>869d45db-d5eb-45b6-bf3b-87d5b84aa467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>::{'input-big': size === 'large', 'input-sm': size === 'small'}</value>
      <webElementGuid>caebc647-07db-40a5-885f-d3b4f6b29d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-maxlength</name>
      <type>Main</type>
      <value>1024</value>
      <webElementGuid>f77cd463-38b2-436f-8ee9-32b7e68ca22f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-minlength</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9d025481-4405-4125-86a3-9c173af5679d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enable-jinja</name>
      <type>Main</type>
      <value>enableJinja</value>
      <webElementGuid>993b4c37-8336-4637-93cf-bf9d8477ddd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enable-record-fields</name>
      <type>Main</type>
      <value>enableRecordFields</value>
      <webElementGuid>f4bda59b-1cec-44ec-b71c-dd86471f0ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>One</value>
      <webElementGuid>4249e2af-38db-4892-a598-83e1d9e9f27c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1064c7ce-21f2-4391-b02e-fe2b1ad29a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>e63deab2-c67e-4937-ac81-eb6190a1b7b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ff3e76ad-6b34-4346-9d51-c64e3c973a8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actorForm-lastname&quot;)</value>
      <webElementGuid>b0b1f16c-b2e8-4316-83ae-c9806d24908c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='actorForm-lastname']</value>
      <webElementGuid>ea813520-7449-4fae-8a47-ec9ffe9bf6f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='admin-pane']/div/div/div/form/div[3]/div/div[3]/div/div[3]/div/div/div[2]/div/div/input</value>
      <webElementGuid>6e3f31be-b3cf-45fa-bd48-6dd9b0489662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>97c5b2ea-3307-4517-a94b-b1080ce847e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'actorForm-lastname' and @type = 'text' and @name = 'lastname' and @title = 'One']</value>
      <webElementGuid>10c7efed-c2e6-4fdf-9a4a-ec9a7a71df65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
