<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Summary</name>
   <tag></tag>
   <elementGuidId>dbb52e99-09d6-4afe-9882-5ce43500eec6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.nav-link.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='admin-pane']/div/div/div[3]/form/div[2]/div/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2b010cdd-932b-4ff9-8b2b-2761dfc76414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>select($event)</value>
      <webElementGuid>41fbbff2-9260-4ec8-b3ef-6cd49ac2763f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link ng-binding</value>
      <webElementGuid>049fabff-f593-4081-a5ac-05e5306b4762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Summary</value>
      <webElementGuid>6333c923-57ee-46dd-a5fb-54e4a9e23b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;admin-pane&quot;)/div[@class=&quot;admin-content ng-scope&quot;]/div[@class=&quot;padding-bottom-xlg clearfix ng-scope&quot;]/div[3]/form[@class=&quot;ng-invalid ng-invalid-required ng-valid-unique ng-dirty ng-valid-parse&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;no-background ng-isolate-scope&quot;]/ul[@class=&quot;nav nav-tabs&quot;]/li[@class=&quot;uib-tab nav-item ng-scope ng-isolate-scope&quot;]/a[@class=&quot;nav-link ng-binding&quot;]</value>
      <webElementGuid>f5299b97-3836-4dcf-bd2b-4b13baf146a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='admin-pane']/div/div/div[3]/form/div[2]/div/ul/li/a</value>
      <webElementGuid>22ce20c9-74f7-4076-80c3-ef39ec962741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Summary')]</value>
      <webElementGuid>501c377e-f23e-4d30-9989-73fafaf11b02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Module change initiated. Awaiting response from tenant.'])[1]/following::a[1]</value>
      <webElementGuid>72733695-506c-473f-a21a-708f4bf6d5f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::a[1]</value>
      <webElementGuid>f1770dd7-2ca6-40de-946a-eae48ec19c47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fields Editor'])[1]/preceding::a[1]</value>
      <webElementGuid>1193a30a-bb4f-40a6-813b-8f204aa12200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Module Name cannot be modified, once it is saved'])[1]/preceding::a[2]</value>
      <webElementGuid>9b14dd3f-26fd-4c9b-9787-435fb3ed1536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Summary']/parent::*</value>
      <webElementGuid>c4e8102e-1a93-4aae-ac85-4e815455ef1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[99]</value>
      <webElementGuid>255c4da1-cf7d-4dba-9652-ef0f680d9cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/ul/li/a</value>
      <webElementGuid>5b4d0398-85bd-4751-8433-046ac6408ace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Summary' or . = 'Summary')]</value>
      <webElementGuid>8344147a-cfea-4bbc-89ae-b36809985044</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
