<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Publish All Modules</name>
   <tag></tag>
   <elementGuidId>6fc88b05-0d6e-41dd-8674-c8e437390f4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'modules-actions-publish' and @type = 'button' and (text() = 'Publish All Modules' or . = 'Publish All Modules')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='modules-actions-publish']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#modules-actions-publish</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4f5d4ed9-2baf-4a33-964b-3df0381c5938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modules-actions-publish</value>
      <webElementGuid>4c61c4e3-fbeb-421c-b4ba-3c423b2649c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>888d251c-80d0-4879-b0e5-22275e492e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm cs-btn pull-right</value>
      <webElementGuid>e0ec2196-3207-4bfc-b359-6dff9da1238c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-show</name>
      <type>Main</type>
      <value>permission.update &amp;&amp; !isDemo</value>
      <webElementGuid>99abd76c-c561-4122-90e1-baac5fd4638d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-disabled</name>
      <type>Main</type>
      <value>(changedModules.length === 0 &amp;&amp; newModules.length === 0 &amp;&amp; deletedModules.length === 0) || processing</value>
      <webElementGuid>e8333002-ebec-4b2a-8b5b-6bc6e5fbe917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>publish()</value>
      <webElementGuid>a79a5f71-438e-4bdd-a0ef-dc3d113a9b7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>88a8d1fb-f3a0-4b0f-90e3-6ac4bf5c435a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Publish All Modules</value>
      <webElementGuid>181c1845-d8f7-4466-bac9-1d759c8b4d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modules-actions-publish&quot;)</value>
      <webElementGuid>aaf1270f-f3b4-4869-beab-a8dfe3cb52e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='modules-actions-publish']</value>
      <webElementGuid>70d684fa-d6fc-4886-9ad0-1dc8a0a86305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='admin-pane']/div/div/div/div/div[2]/button[2]</value>
      <webElementGuid>acea8c61-b583-4f6e-a907-3af230af8438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Revert All'])[1]/following::button[1]</value>
      <webElementGuid>e11f1494-dd5a-408d-b436-4f42b499283e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last published: 7 days ago'])[1]/following::button[2]</value>
      <webElementGuid>3ea00ee0-c497-4e72-a545-8512fde9cf98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Publish All Modules']/parent::*</value>
      <webElementGuid>4f5b8dfd-d245-42f6-9f12-439a010bb7e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/button[2]</value>
      <webElementGuid>c26f1192-8566-45f0-bd47-85ccd9b22650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'modules-actions-publish' and @type = 'button' and (text() = 'Publish All Modules' or . = 'Publish All Modules')]</value>
      <webElementGuid>6c951b76-0a19-4f21-9abc-3f5bc2ae2901</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
