<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Fields_attribute-add-btn-top</name>
   <tag></tag>
   <elementGuidId>af6fc1e6-06b3-41f9-b8b2-a96d6e928461</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#attribute-add-btn-top</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='attribute-add-btn-top']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9e5d0557-6fe2-4a85-a7bd-a65fdc32cc17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>attribute-add-btn-top</value>
      <webElementGuid>81995d62-30fb-47c7-acc0-8fecabfb3bf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-primary</value>
      <webElementGuid>0611e154-a279-4aaf-b055-1903711cf7b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1804b1e8-0e0f-4d94-8960-86f6b7c538ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>addAttribute(true)</value>
      <webElementGuid>94ce1eb4-2b73-4871-84fc-659dd61d3ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attribute-add-btn-top&quot;)</value>
      <webElementGuid>8a0b0759-b332-4d22-8b25-aa8c55b64589</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='attribute-add-btn-top']</value>
      <webElementGuid>942afd4f-d848-4652-a07b-8d253c31975c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='admin-pane']/div/div/div[3]/form/div[2]/div/div/div[2]/div/div/div/div/div[2]/button</value>
      <webElementGuid>00e37b08-3ddb-4f55-9c31-2732c9493c40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fields'])[1]/following::button[1]</value>
      <webElementGuid>7d14f737-450f-4b2c-99ec-637f1fb4b31a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Field'])[1]/preceding::button[1]</value>
      <webElementGuid>b3e8b40b-6969-4430-8913-c38926ee033d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Properties'])[1]/preceding::button[1]</value>
      <webElementGuid>a49a2803-1351-4614-80c1-a31e675551dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div/div[2]/div/div/div/div/div[2]/button</value>
      <webElementGuid>69c602d1-68b8-473f-ac49-3c0695bbecd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'attribute-add-btn-top' and @type = 'button']</value>
      <webElementGuid>386d970d-237f-4c2f-8f99-08e7174de47e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
