<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Card NumberCVV</name>
   <tag></tag>
   <elementGuidId>efed9215-c94f-4ac3-8588-c91bfd763f2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#displayName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='displayName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>781142b5-8e78-4304-a124-d973fe861d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-multi-select ui-select-container ui-select-multiple ui-select-bootstrap dropdown form-control ng-scope ng-dirty ng-empty ng-invalid ng-invalid-required ng-touched open</value>
      <webElementGuid>7c9fee5c-dc26-45a4-ad5f-ceb8416b32e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{open: $select.open}</value>
      <webElementGuid>d9e2c45f-bc3f-4aaa-b6af-66955ba5d352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>displayName</value>
      <webElementGuid>3e295f3e-223b-47b6-9f84-86b0f3eeb25b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>displayName</value>
      <webElementGuid>f67dd910-0867-41b4-891b-b8d4cfc179a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>entity._simpleDisplayName</value>
      <webElementGuid>7e888cba-f247-4bbd-b3d4-a2b40afd3d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>06851345-462c-4a8d-8a69-f73f79cb4ffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>append-to-body</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>aa12efc4-1b7c-488e-9033-cdeb173d7e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>$select.activate()</value>
      <webElementGuid>ce1ed02b-5c79-4543-b674-90d7a51f9322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fc7414c3-630c-4091-ae48-4a7fa1f1751c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5e1c687d-6d10-468c-a73e-f75abdbefbbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>72be30d4-ca80-40a3-b6f5-be041e07672d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>054ec8e2-8e1f-4324-91f6-1070475c8a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2044da2d-a87f-4cec-afb5-e096f777502f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Card NumberCVV</value>
      <webElementGuid>6eaab033-7217-4248-baaa-1fc713787827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;displayName&quot;)</value>
      <webElementGuid>102d32f2-0898-4fed-ab2c-b6984dadb8fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='displayName']</value>
      <webElementGuid>110ef52c-f3f6-4e33-8599-33539f0a7a3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='admin-pane']/div/div/div[3]/form/div[2]/div/div/div/data-ng-form/div[5]/div/div/div/div/div</value>
      <webElementGuid>f18a6da7-9acd-4458-b35a-bda743b3b01e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::div[3]</value>
      <webElementGuid>4df7d925-3d66-419f-9a2b-1876b900964b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//data-ng-form/div[5]/div/div/div/div/div</value>
      <webElementGuid>b11b35af-5f53-4e69-aeea-0271eb254593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@name = 'displayName' and @id = 'displayName' and (text() = 'Card NumberCVV' or . = 'Card NumberCVV')]</value>
      <webElementGuid>a619db50-c2fe-4d6a-a7db-5103e0c2d5ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
