<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__displayName</name>
   <tag></tag>
   <elementGuidId>18a55708-33e5-42a0-9784-0fd19f1101f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#displayName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='displayName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e98ba3ac-28d1-467b-a37f-9f7db70d8321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-multi-select ui-select-container ui-select-multiple ui-select-bootstrap dropdown form-control ng-scope ng-dirty ng-empty ng-invalid ng-invalid-required ng-touched</value>
      <webElementGuid>e71834f9-9e7d-4568-b1ad-5920296abddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{open: $select.open}</value>
      <webElementGuid>4a37b457-f4c0-4d6d-9a4c-089f5fbf4487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>displayName</value>
      <webElementGuid>64d5abbb-c6f3-4be6-82d3-08220b571e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>displayName</value>
      <webElementGuid>060578f1-ad5f-4cb6-9014-e4f9576eab5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>entity._simpleDisplayName</value>
      <webElementGuid>48b03a46-62aa-4302-9cb1-27d19cf5e484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>863a8cf1-c661-43bf-b35b-45c08c0f57df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>append-to-body</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9b87b605-e7cb-486e-a95c-3f0058f36fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>$select.activate()</value>
      <webElementGuid>2f237b95-df1c-4d4f-8aa6-f7ce5b34e16a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7713cb48-da27-49c7-97ab-01e80597bd13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7b0881e3-d4b8-4724-865c-90124d095c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d4ebe978-1718-4dbc-8d7d-6c95cecbbb99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>02aec68e-4e22-4571-9b8e-24f73dc36d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>64487750-4221-42d6-9186-2031ecdd7285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;displayName&quot;)</value>
      <webElementGuid>a9188083-c59d-492c-bfea-1ced2896392c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='displayName']</value>
      <webElementGuid>c8c3878f-12bb-4264-a326-2b915e5291a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='admin-pane']/div/div/div[3]/form/div[2]/div/div/div/data-ng-form/div[5]/div/div/div/div/div</value>
      <webElementGuid>4ed78af7-a3c8-4a8c-b7e3-50d6fe2384e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::div[3]</value>
      <webElementGuid>6ab1a0e9-759b-4392-9be5-9d1c07405f76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='{}'])[1]/preceding::div[5]</value>
      <webElementGuid>b289c7f4-d5f0-4ef6-b1bf-af85b694e550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Record Uniqueness'])[1]/preceding::div[5]</value>
      <webElementGuid>7a1d1b54-f8e0-486c-8dc6-8d000603bf36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//data-ng-form/div[5]/div/div/div/div/div</value>
      <webElementGuid>a6771729-ca06-436e-8fca-10c8c5e2b941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@name = 'displayName' and @id = 'displayName']</value>
      <webElementGuid>a419e37f-ce52-4225-9158-2543b31937d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
