<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Singular_singularName</name>
   <tag></tag>
   <elementGuidId>08edbdd1-4d20-4b0a-bcf2-ce9b800a45ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#singularName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='singularName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>34711ed2-85e8-4ff4-919b-1ca34c12a0d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>singularName</value>
      <webElementGuid>8d0d4610-98e1-4ffd-8f04-2b12e1a3c27f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>37657de5-de22-475c-ad64-29a901767251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>singularName</value>
      <webElementGuid>4fd809a2-3a4e-470d-9c08-3c9b559a7e5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>entity.fields.descriptions.value.singular</value>
      <webElementGuid>a5253504-f571-43b7-8500-c06068ba60d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ec78e7d1-d423-4472-9313-0871ac7f885f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cs-unique</name>
      <type>Main</type>
      <value>singularNameList</value>
      <webElementGuid>7896830e-3ce3-4f22-b175-8e1efbc6e329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-readonly</name>
      <type>Main</type>
      <value>module.uuid</value>
      <webElementGuid>ef2dc02b-812a-4347-9d37-c1921636c03a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-isolate-scope ng-empty ng-invalid ng-invalid-required ng-valid-unique</value>
      <webElementGuid>2d3042b5-d576-44a0-96c8-54ad30f06a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-blur</name>
      <type>Main</type>
      <value>buildModuleData()</value>
      <webElementGuid>5e0d5b0d-cdef-4417-9deb-0b9954c06b6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>fbca3377-579f-4ef8-94da-93da0cdf817a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3ae7193d-7a09-44aa-a8d7-a38bc6744c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;singularName&quot;)</value>
      <webElementGuid>e37a4bc9-279e-4e69-ae65-db23368f0960</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='singularName']</value>
      <webElementGuid>9ed0847e-4502-4582-a428-b0b311b8192b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='admin-pane']/div/div/div[3]/form/div[2]/div/div/div/data-ng-form/div[4]/div/div/div/input</value>
      <webElementGuid>914e21c0-a155-433b-a331-8a8b5412e0e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>5d027aed-0d05-4de3-84a2-f34ee1d05697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'singularName' and @type = 'text' and @name = 'singularName']</value>
      <webElementGuid>f57106e5-1f29-44d9-b17c-c4fe376b46e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
