<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Create new moduleAgentsAlertsAnnounc_2c099f</name>
   <tag></tag>
   <elementGuidId>7c7939b4-aa06-4708-8148-e57d6ae36ed7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modules-select</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e7a7f978-9789-42fe-b865-593f17a918df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-valid ng-not-empty</value>
      <webElementGuid>a235c1e6-ef3a-46d5-ad42-4abe6ff514bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modules-select</value>
      <webElementGuid>c99915e2-fd33-4706-8abc-be7e045f877e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>modulesSelect</value>
      <webElementGuid>594e4c00-e344-4d0a-9839-73d8eb8bd60d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>selectedModule</value>
      <webElementGuid>02ce7734-de1d-4746-9b76-e6f8bb4f847a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-options</name>
      <type>Main</type>
      <value>option as (option._changed ? '* ' : '') + option.descriptions.plural for option in stagingModulesList | orderBy : 'type' track by option.uuid</value>
      <webElementGuid>77f1ff60-dced-413f-b1b8-cb049c21ebf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-change</name>
      <type>Main</type>
      <value>moduleChanged(selectedModule.uuid)</value>
      <webElementGuid>752365a3-893d-4f46-806e-cda627fbf12d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d1d4c3fc-fdb1-4b92-9678-730b5442af99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+ Create new moduleAgentsAlertsAnnouncementsAppliancesApprovalsAssetsAttachmentsCampaignsCommentCommunicationsCompaniesCredit CardsEventsQueuesHuntsIncidentsIndicatorsPeopleRoutersSaved ReportsShiftsSLA TemplatesTasksTenantsWar Rooms</value>
      <webElementGuid>9c4a666f-693b-4160-a2c5-30361803ea39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modules-select&quot;)</value>
      <webElementGuid>82a3913f-eab8-4823-a4a0-db2bdda53f49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='modules-select']</value>
      <webElementGuid>3c9d5c7d-b91f-40df-b5f0-870f9726ccb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='admin-pane']/div/div/div[3]/div/div/div/select</value>
      <webElementGuid>b7b2eefd-5ae6-4c79-aa00-439869810126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Audit Log'])[2]/preceding::select[1]</value>
      <webElementGuid>9fdfae7c-c394-4001-84bb-d73ae500b255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/select</value>
      <webElementGuid>6a231c11-3ec8-415a-b2b4-5cead52af23d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'modules-select' and @name = 'modulesSelect' and (text() = '+ Create new moduleAgentsAlertsAnnouncementsAppliancesApprovalsAssetsAttachmentsCampaignsCommentCommunicationsCompaniesCredit CardsEventsQueuesHuntsIncidentsIndicatorsPeopleRoutersSaved ReportsShiftsSLA TemplatesTasksTenantsWar Rooms' or . = '+ Create new moduleAgentsAlertsAnnouncementsAppliancesApprovalsAssetsAttachmentsCampaignsCommentCommunicationsCompaniesCredit CardsEventsQueuesHuntsIncidentsIndicatorsPeopleRoutersSaved ReportsShiftsSLA TemplatesTasksTenantsWar Rooms')]</value>
      <webElementGuid>a7b0a2d3-bf48-4091-8abd-cf1552abc25c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
