<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Fields_icon icon-add</name>
   <tag></tag>
   <elementGuidId>a743223d-8359-4015-b8ee-182858f3c080</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.icon.icon-add</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='attribute-add-btn-top']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ef27c0b2-e271-4c83-8e20-5b4a2f94038f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon icon-add</value>
      <webElementGuid>360110a5-2e7b-41e5-966b-1a5451235cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attribute-add-btn-top&quot;)/span[@class=&quot;icon icon-add&quot;]</value>
      <webElementGuid>b01ca90f-caa2-48af-8322-a3f031965eb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='attribute-add-btn-top']/span</value>
      <webElementGuid>f0aeef4a-f0c8-4cd0-844b-a63af0ae4976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/span</value>
      <webElementGuid>7fedccb9-36fb-4b1b-afa7-cbeb4e933fff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
