<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add Playbook</name>
   <tag></tag>
   <elementGuidId>0645c97d-177f-46c0-a271-0339947b1760</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-new</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-new']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8a0f7d58-7ea8-41f9-aa31-6e067a1b3318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-new</value>
      <webElementGuid>5548083f-ef6c-40c8-89d9-863b4dd177b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-action btn btn-sm cs-btn-100 ng-binding ng-scope btn-primary</value>
      <webElementGuid>7e313be8-bf22-42e5-b035-42905f3301c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-disabled</name>
      <type>Main</type>
      <value>button.disabled || $parent.$parent.disabled</value>
      <webElementGuid>446fab6e-d0d6-4e16-9f89-3d6e9936005c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-if</name>
      <type>Main</type>
      <value>!button.menuItems</value>
      <webElementGuid>db3c2cd3-51b9-4b0f-a898-efac59bd2729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>::[button.class, 'btn-sm']</value>
      <webElementGuid>58693fcb-d5e7-437c-9162-792cb51926ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>26e18373-80c3-4a80-8271-04bbea904621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>button.onClick()</value>
      <webElementGuid>180e3e8b-28e1-4c82-ba67-20fea49301af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-hide</name>
      <type>Main</type>
      <value>button.hide</value>
      <webElementGuid>de022f81-105a-4fbb-aea0-2ea7b1f7c05f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autofocus</name>
      <type>Main</type>
      <value>button.text === 'Cancel'</value>
      <webElementGuid>345d3202-f1d8-4baa-9c1b-8cc1abc79afd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>30bf0559-1be3-4a4f-bfd5-3bfb882b3647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Add Playbook</value>
      <webElementGuid>06f3f787-39ec-4c48-8ca3-1da5bfe914cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-new&quot;)</value>
      <webElementGuid>c552b51c-8b69-4cb2-9954-65464079500b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-new']</value>
      <webElementGuid>816da073-d394-4473-a4c2-5b8819ef808c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list-pane']/div/div/div/div/div[2]/div/div/div/div/div[3]/div[2]/div/div/button</value>
      <webElementGuid>adceb664-cff8-440c-b4d1-73dcc19691f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[6]/following::button[2]</value>
      <webElementGuid>b3a4ccb1-b809-45d4-ae91-337b1451827c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--'])[3]/following::button[2]</value>
      <webElementGuid>e1f7b504-fe9a-4eaa-aa0e-2be9ed4e5c55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Playbook']/parent::*</value>
      <webElementGuid>dc4a0f06-3183-40e9-8ab3-e94c2a888759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/button</value>
      <webElementGuid>c29410f4-9f0d-464b-bdf6-dd90d09a8ca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-new' and @type = 'button' and (text() = '  Add Playbook' or . = '  Add Playbook')]</value>
      <webElementGuid>38b63150-c54d-4df0-85ca-95a7850a2959</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
