<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__name_1</name>
   <tag></tag>
   <elementGuidId>6beaa3c5-3045-4984-8c66-5c8adaa0a83f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#newForm-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='newForm-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b5c832c-85e1-42e1-9764-10cfce3d605a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-hide</name>
      <type>Main</type>
      <value>field.value.includes('resolveVault')</value>
      <webElementGuid>f205e6bf-c8d9-4743-b863-c423e4538ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-required</name>
      <type>Main</type>
      <value>field.required</value>
      <webElementGuid>0ad68843-b053-465c-869e-64e9df0e803b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>newForm-name</value>
      <webElementGuid>4e4b6f55-4df8-4824-965e-9d9827bb1578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1432ddad-b4a9-4559-b810-b0f8e2ee5334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>dadfd370-3dbc-45cd-b295-7b1a6ef8c691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>736d220c-da95-4e58-87e0-3ec71170b9d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control  ng-isolate-scope ng-not-empty ng-dirty ng-valid-parse ng-valid ng-valid-required grid-active-filter</value>
      <webElementGuid>bb627284-3a34-4785-9b51-8655f1e5bb70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0b877a59-793c-46de-96f6-d8f30c6b2eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-readonly</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>a6292e5a-f107-4bd2-9596-f8292b3a3a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-change</name>
      <type>Main</type>
      <value>changeMethod(value, field)</value>
      <webElementGuid>aa27cf90-7446-466d-b1ab-516d158b3da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-blur</name>
      <type>Main</type>
      <value>blurMethod(value)</value>
      <webElementGuid>ebfb27c2-386e-465c-a015-acc0798d4b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-focus</name>
      <type>Main</type>
      <value>focusMethod($event)</value>
      <webElementGuid>74941a86-0964-4a26-9591-447025868661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>::{'input-big': size === 'large', 'input-sm': size === 'small'}</value>
      <webElementGuid>c3a9bd03-f464-4ab9-9f42-a395989ce9fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-maxlength</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4d38dc99-a0e4-443d-b53f-4f856c8f5108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-minlength</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>963375e5-f046-48e4-9b58-78f46a04d2c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enable-jinja</name>
      <type>Main</type>
      <value>enableJinja</value>
      <webElementGuid>b9e5a36f-3abd-4372-96f1-f02bbe763121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enable-record-fields</name>
      <type>Main</type>
      <value>enableRecordFields</value>
      <webElementGuid>97018167-44d5-4b27-88bc-e904055f3cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>A</value>
      <webElementGuid>5b2dfaf2-bc1f-4e42-a56f-e0a3661d6e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>01bf314e-ccd4-41f7-8050-b00b6f6e6c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>e719315b-bafb-4762-865d-b444ad62c3d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f82a1993-b929-4c25-bb60-f513aa28cdaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;newForm-name&quot;)</value>
      <webElementGuid>366a0ae9-94af-46bc-bb7b-6aa22a43f332</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='newForm-name']</value>
      <webElementGuid>7f616e34-e7fa-43e0-ad27-52c543ed47fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='newForm']/div[2]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>a8167ce7-001e-4db1-b382-95093e3977a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>78d644d7-d7a1-4ad7-9745-992db8a4a5c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'newForm-name' and @type = 'text' and @name = 'name' and @title = 'A']</value>
      <webElementGuid>615b095b-b6eb-477f-a0f7-11cb64402116</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
